
code U8 QMAP_4K_UFSC[QM_INPUTTYPE_NUM_UFSC][PQ_IP_NUM_UFSC]=
{
    #if PQ_QM_HMDI
    {//4K 4K2K_RGB444, 0
    PQ_IP_INIT_FAC_Type0_UFSC, PQ_IP_VSP_Y_Bypass_UFSC, PQ_IP_VSP_C_Bypass_UFSC, PQ_IP_VSP_CoRing_OFF_UFSC, PQ_IP_VSP_Dither_OFF_UFSC, 
    PQ_IP_VSP_PreVBound_OFF_UFSC, PQ_IP_HSP_Y_Bypass_UFSC, PQ_IP_HSP_C_Bypass_UFSC, PQ_IP_HSP_CoRing_OFF_UFSC, PQ_IP_HSP_DeRing_OFF_UFSC, 
    PQ_IP_HSP_Dither_OFF_UFSC, PQ_IP_HnonLinear_OFF_UFSC, PQ_IP_HSP_Y_COEFF_InvSinc4Tc4p4Fc85Apass0001Astop40_UFSC, PQ_IP_HSP_C_COEFF_InvSinc4Tc4p4Fc85Apass0001Astop40_UFSC, PQ_IP_VIP_4K_4K2K_UFSC, 
    PQ_IP_SC_End_End_UFSC, 
    },
    #endif
    #if PQ_QM_HMDI
    {//4K 4K2K_YUV444, 1
    PQ_IP_INIT_FAC_Type0_UFSC, PQ_IP_VSP_Y_Bypass_UFSC, PQ_IP_VSP_C_Bypass_UFSC, PQ_IP_VSP_CoRing_OFF_UFSC, PQ_IP_VSP_Dither_OFF_UFSC, 
    PQ_IP_VSP_PreVBound_OFF_UFSC, PQ_IP_HSP_Y_Bypass_UFSC, PQ_IP_HSP_C_Bypass_UFSC, PQ_IP_HSP_CoRing_OFF_UFSC, PQ_IP_HSP_DeRing_OFF_UFSC, 
    PQ_IP_HSP_Dither_OFF_UFSC, PQ_IP_HnonLinear_OFF_UFSC, PQ_IP_HSP_Y_COEFF_InvSinc4Tc4p4Fc85Apass0001Astop40_UFSC, PQ_IP_HSP_C_COEFF_InvSinc4Tc4p4Fc85Apass0001Astop40_UFSC, PQ_IP_VIP_4K_4K2K_UFSC, 
    PQ_IP_SC_End_End_UFSC, 
    },
    #endif
    #if PQ_QM_HMDI
    {//4K 4K2K_YUV422, 2
    PQ_IP_INIT_FAC_Type0_UFSC, PQ_IP_VSP_Y_Bypass_UFSC, PQ_IP_VSP_C_Bypass_UFSC, PQ_IP_VSP_CoRing_OFF_UFSC, PQ_IP_VSP_Dither_OFF_UFSC, 
    PQ_IP_VSP_PreVBound_OFF_UFSC, PQ_IP_HSP_Y_Bypass_UFSC, PQ_IP_HSP_C_Bypass_UFSC, PQ_IP_HSP_CoRing_OFF_UFSC, PQ_IP_HSP_DeRing_OFF_UFSC, 
    PQ_IP_HSP_Dither_OFF_UFSC, PQ_IP_HnonLinear_OFF_UFSC, PQ_IP_HSP_Y_COEFF_InvSinc4Tc4p4Fc85Apass0001Astop40_UFSC, PQ_IP_HSP_C_COEFF_InvSinc4Tc4p4Fc85Apass0001Astop40_UFSC, PQ_IP_VIP_4K_4K2K_UFSC, 
    PQ_IP_SC_End_End_UFSC, 
    },
    #endif
    #if PQ_QM_HMDI
    {//4K FHD_RGB444, 3
    PQ_IP_INIT_FAC_Type1_UFSC, PQ_IP_VSP_Y_Bilinear_UFSC, PQ_IP_VSP_C_Bilinear_UFSC, PQ_IP_VSP_CoRing_OFF_UFSC, PQ_IP_VSP_Dither_OFF_UFSC, 
    PQ_IP_VSP_PreVBound_OFF_UFSC, PQ_IP_HSP_Y_Y_4Tap_UFSC, PQ_IP_HSP_C_Y_4Tap_UFSC, PQ_IP_HSP_CoRing_OFF_UFSC, PQ_IP_HSP_DeRing_OFF_UFSC, 
    PQ_IP_HSP_Dither_OFF_UFSC, PQ_IP_HnonLinear_OFF_UFSC, PQ_IP_HSP_Y_COEFF_InvSinc4Tc4p4Fc85Apass0001Astop40_UFSC, PQ_IP_HSP_C_COEFF_InvSinc4Tc4p4Fc85Apass0001Astop40_UFSC, PQ_IP_VIP_4K_OFF_UFSC, 
    PQ_IP_SC_End_End_UFSC, 
    },
    #endif
    #if PQ_QM_HMDI
    {//4K FHD_YUV444, 4
    PQ_IP_INIT_FAC_Type1_UFSC, PQ_IP_VSP_Y_Bilinear_UFSC, PQ_IP_VSP_C_Bilinear_UFSC, PQ_IP_VSP_CoRing_OFF_UFSC, PQ_IP_VSP_Dither_OFF_UFSC, 
    PQ_IP_VSP_PreVBound_OFF_UFSC, PQ_IP_HSP_Y_Y_4Tap_UFSC, PQ_IP_HSP_C_C_4Tap_UFSC, PQ_IP_HSP_CoRing_OFF_UFSC, PQ_IP_HSP_DeRing_DR1_UFSC, 
    PQ_IP_HSP_Dither_OFF_UFSC, PQ_IP_HnonLinear_OFF_UFSC, PQ_IP_HSP_Y_COEFF_InvSinc4Tc4p4Fc85Apass0001Astop40_UFSC, PQ_IP_HSP_C_COEFF_InvSinc4Tc4p4Fc85Apass0001Astop40_UFSC, PQ_IP_VIP_4K_OFF_UFSC, 
    PQ_IP_SC_End_End_UFSC, 
    },
    #endif
    #if PQ_QM_HMDI
    {//4K FHD_YUV422, 5
    PQ_IP_INIT_FAC_Type1_UFSC, PQ_IP_VSP_Y_Bilinear_UFSC, PQ_IP_VSP_C_Bilinear_UFSC, PQ_IP_VSP_CoRing_OFF_UFSC, PQ_IP_VSP_Dither_OFF_UFSC, 
    PQ_IP_VSP_PreVBound_OFF_UFSC, PQ_IP_HSP_Y_Y_4Tap_UFSC, PQ_IP_HSP_C_C_4Tap_UFSC, PQ_IP_HSP_CoRing_OFF_UFSC, PQ_IP_HSP_DeRing_DR1_UFSC, 
    PQ_IP_HSP_Dither_OFF_UFSC, PQ_IP_HnonLinear_OFF_UFSC, PQ_IP_HSP_Y_COEFF_InvSinc4Tc4p4Fc85Apass0001Astop40_UFSC, PQ_IP_HSP_C_COEFF_InvSinc4Tc4p4Fc85Apass0001Astop40_UFSC, PQ_IP_VIP_4K_OFF_UFSC, 
    PQ_IP_SC_End_End_UFSC, 
    },
    #endif
    #if PQ_QM_HMDI
    {//4K FSC_3D, 6
    PQ_IP_INIT_FAC_Type0_UFSC, PQ_IP_VSP_Y_Bypass_UFSC, PQ_IP_VSP_C_Bypass_UFSC, PQ_IP_VSP_CoRing_OFF_UFSC, PQ_IP_VSP_Dither_OFF_UFSC, 
    PQ_IP_VSP_PreVBound_OFF_UFSC, PQ_IP_HSP_Y_Bypass_UFSC, PQ_IP_HSP_C_Bypass_UFSC, PQ_IP_HSP_CoRing_OFF_UFSC, PQ_IP_HSP_DeRing_OFF_UFSC, 
    PQ_IP_HSP_Dither_OFF_UFSC, PQ_IP_HnonLinear_OFF_UFSC, PQ_IP_HSP_Y_COEFF_InvSinc4Tc4p4Fc85Apass0001Astop40_UFSC, PQ_IP_HSP_C_COEFF_InvSinc4Tc4p4Fc85Apass0001Astop40_UFSC, PQ_IP_VIP_4K_OFF_UFSC, 
    PQ_IP_SC_End_End_UFSC, 
    },
    #endif
    #if PQ_QM_HMDI
    {//4K 4K2K_RGB444_DS, 7
    PQ_IP_INIT_FAC_Type0_UFSC, PQ_IP_VSP_Y_Bypass_UFSC, PQ_IP_VSP_C_Bypass_UFSC, PQ_IP_VSP_CoRing_OFF_UFSC, PQ_IP_VSP_Dither_OFF_UFSC, 
    PQ_IP_VSP_PreVBound_OFF_UFSC, PQ_IP_HSP_Y_Bypass_UFSC, PQ_IP_HSP_C_Bypass_UFSC, PQ_IP_HSP_CoRing_OFF_UFSC, PQ_IP_HSP_DeRing_OFF_UFSC, 
    PQ_IP_HSP_Dither_OFF_UFSC, PQ_IP_HnonLinear_OFF_UFSC, PQ_IP_HSP_Y_COEFF_InvSinc4Tc4p4Fc85Apass0001Astop40_UFSC, PQ_IP_HSP_C_COEFF_InvSinc4Tc4p4Fc85Apass0001Astop40_UFSC, PQ_IP_VIP_4K_4K2K_UFSC, 
    PQ_IP_SC_End_End_UFSC, 
    },
    #endif
    #if PQ_QM_HMDI
    {//4K 4K2K_YUV444_DS, 8
    PQ_IP_INIT_FAC_Type0_UFSC, PQ_IP_VSP_Y_Bypass_UFSC, PQ_IP_VSP_C_Bypass_UFSC, PQ_IP_VSP_CoRing_OFF_UFSC, PQ_IP_VSP_Dither_OFF_UFSC, 
    PQ_IP_VSP_PreVBound_OFF_UFSC, PQ_IP_HSP_Y_Bypass_UFSC, PQ_IP_HSP_C_Bypass_UFSC, PQ_IP_HSP_CoRing_OFF_UFSC, PQ_IP_HSP_DeRing_OFF_UFSC, 
    PQ_IP_HSP_Dither_OFF_UFSC, PQ_IP_HnonLinear_OFF_UFSC, PQ_IP_HSP_Y_COEFF_InvSinc4Tc4p4Fc85Apass0001Astop40_UFSC, PQ_IP_HSP_C_COEFF_InvSinc4Tc4p4Fc85Apass0001Astop40_UFSC, PQ_IP_VIP_4K_4K2K_UFSC, 
    PQ_IP_SC_End_End_UFSC, 
    },
    #endif
    #if PQ_QM_HMDI
    {//4K 4K2K_YUV422_DS, 9
    PQ_IP_INIT_FAC_Type0_UFSC, PQ_IP_VSP_Y_Bypass_UFSC, PQ_IP_VSP_C_Bypass_UFSC, PQ_IP_VSP_CoRing_OFF_UFSC, PQ_IP_VSP_Dither_OFF_UFSC, 
    PQ_IP_VSP_PreVBound_OFF_UFSC, PQ_IP_HSP_Y_Bypass_UFSC, PQ_IP_HSP_C_Bypass_UFSC, PQ_IP_HSP_CoRing_OFF_UFSC, PQ_IP_HSP_DeRing_OFF_UFSC, 
    PQ_IP_HSP_Dither_OFF_UFSC, PQ_IP_HnonLinear_OFF_UFSC, PQ_IP_HSP_Y_COEFF_InvSinc4Tc4p4Fc85Apass0001Astop40_UFSC, PQ_IP_HSP_C_COEFF_InvSinc4Tc4p4Fc85Apass0001Astop40_UFSC, PQ_IP_VIP_4K_4K2K_UFSC, 
    PQ_IP_SC_End_End_UFSC, 
    },
    #endif
    #if PQ_QM_HMDI
    {//4K FHD_RGB444_DS, 10
    PQ_IP_INIT_FAC_Type1_UFSC, PQ_IP_VSP_Y_Bilinear_UFSC, PQ_IP_VSP_C_Bilinear_UFSC, PQ_IP_VSP_CoRing_OFF_UFSC, PQ_IP_VSP_Dither_OFF_UFSC, 
    PQ_IP_VSP_PreVBound_OFF_UFSC, PQ_IP_HSP_Y_Y_4Tap_UFSC, PQ_IP_HSP_C_Y_4Tap_UFSC, PQ_IP_HSP_CoRing_OFF_UFSC, PQ_IP_HSP_DeRing_OFF_UFSC, 
    PQ_IP_HSP_Dither_OFF_UFSC, PQ_IP_HnonLinear_OFF_UFSC, PQ_IP_HSP_Y_COEFF_InvSinc4Tc4p4Fc85Apass0001Astop40_UFSC, PQ_IP_HSP_C_COEFF_InvSinc4Tc4p4Fc85Apass0001Astop40_UFSC, PQ_IP_VIP_4K_OFF_UFSC, 
    PQ_IP_SC_End_End_UFSC, 
    },
    #endif
    #if PQ_QM_HMDI
    {//4K FHD_YUV444_DS, 11
    PQ_IP_INIT_FAC_Type1_UFSC, PQ_IP_VSP_Y_Bilinear_UFSC, PQ_IP_VSP_C_Bilinear_UFSC, PQ_IP_VSP_CoRing_OFF_UFSC, PQ_IP_VSP_Dither_OFF_UFSC, 
    PQ_IP_VSP_PreVBound_OFF_UFSC, PQ_IP_HSP_Y_Y_4Tap_UFSC, PQ_IP_HSP_C_C_4Tap_UFSC, PQ_IP_HSP_CoRing_OFF_UFSC, PQ_IP_HSP_DeRing_DR1_UFSC, 
    PQ_IP_HSP_Dither_OFF_UFSC, PQ_IP_HnonLinear_OFF_UFSC, PQ_IP_HSP_Y_COEFF_InvSinc4Tc4p4Fc85Apass0001Astop40_UFSC, PQ_IP_HSP_C_COEFF_InvSinc4Tc4p4Fc85Apass0001Astop40_UFSC, PQ_IP_VIP_4K_OFF_UFSC, 
    PQ_IP_SC_End_End_UFSC, 
    },
    #endif
    #if PQ_QM_HMDI
    {//4K FHD_YUV422_DS, 12
    PQ_IP_INIT_FAC_Type1_UFSC, PQ_IP_VSP_Y_Bilinear_UFSC, PQ_IP_VSP_C_Bilinear_UFSC, PQ_IP_VSP_CoRing_OFF_UFSC, PQ_IP_VSP_Dither_OFF_UFSC, 
    PQ_IP_VSP_PreVBound_OFF_UFSC, PQ_IP_HSP_Y_Y_4Tap_UFSC, PQ_IP_HSP_C_C_4Tap_UFSC, PQ_IP_HSP_CoRing_OFF_UFSC, PQ_IP_HSP_DeRing_DR1_UFSC, 
    PQ_IP_HSP_Dither_OFF_UFSC, PQ_IP_HnonLinear_OFF_UFSC, PQ_IP_HSP_Y_COEFF_InvSinc4Tc4p4Fc85Apass0001Astop40_UFSC, PQ_IP_HSP_C_COEFF_InvSinc4Tc4p4Fc85Apass0001Astop40_UFSC, PQ_IP_VIP_4K_OFF_UFSC, 
    PQ_IP_SC_End_End_UFSC, 
    },
    #endif
    #if PQ_QM_HMDI
    {//4K FSC_3D_DS, 13
    PQ_IP_INIT_FAC_Type0_UFSC, PQ_IP_VSP_Y_Bypass_UFSC, PQ_IP_VSP_C_Bypass_UFSC, PQ_IP_VSP_CoRing_OFF_UFSC, PQ_IP_VSP_Dither_OFF_UFSC, 
    PQ_IP_VSP_PreVBound_OFF_UFSC, PQ_IP_HSP_Y_Bypass_UFSC, PQ_IP_HSP_C_Bypass_UFSC, PQ_IP_HSP_CoRing_OFF_UFSC, PQ_IP_HSP_DeRing_OFF_UFSC, 
    PQ_IP_HSP_Dither_OFF_UFSC, PQ_IP_HnonLinear_OFF_UFSC, PQ_IP_HSP_Y_COEFF_InvSinc4Tc4p4Fc85Apass0001Astop40_UFSC, PQ_IP_HSP_C_COEFF_InvSinc4Tc4p4Fc85Apass0001Astop40_UFSC, PQ_IP_VIP_4K_OFF_UFSC, 
    PQ_IP_SC_End_End_UFSC, 
    },
    #endif
};

