#include <linux/kernel.h>
#include <linux/string.h>
#include <linux/slab.h>
#include <linux/compat.h>
#include <asm/uaccess.h>

#include "VDEC_EX_adp.h"
#include "utopia.h"
#include "utopia_adp.h"
//#include "drvVDEC.h"
#include "apiVDEC_EX.h"
#include "apiVDEC_EX_v2.h"

#include "MsDevice.h"


#ifdef MSOS_TYPE_LINUX_KERNEL

#ifndef CPY_FROM_USER
#define CPY_FROM_USER                   copy_from_user
#endif
#ifndef CPY_to_USER
#define CPY_to_USER                     copy_to_user
#endif

#else
#ifndef CPY_FROM_USER
#define CPY_FROM_USER                   memcpy
#endif
#ifndef CPY_to_USER
#define CPY_to_USER                     memcpy
#endif

#endif

#if (defined(MSOS_TYPE_LINUX_KERNEL) && defined(CONFIG_COMPAT))
    #define IS_CMP_TASK()                                           is_compat_task()
    #define CMP_CPY_FROM_USER(a,b,c)                                if(copy_from_user(a, compat_ptr((unsigned long)b), c) != 0)  {  break; }
    #define CMP_CPY_TO_USER(a,b,c)                                  if(copy_to_user(compat_ptr((unsigned long)a), b, c) != 0) { break;  }
#else
    #define IS_CMP_TASK()                                             (FALSE)
    #define CMP_CPY_FROM_USER                                       CPY_FROM_USER
    #define CMP_CPY_TO_USER                                         CPY_to_USER
#endif

typedef struct DLL_PACKED
{
    VDEC_EX_V2_User_Cmd     eUserCmd;
    VDEC_EX_V2_StreamId*    StreamID;
    void* pRet;
    //void* param[1];  // at most 8 param
}VDEC_EX_V2_IO_Param_0;

typedef struct DLL_PACKED
{
    VDEC_EX_V2_User_Cmd     eUserCmd;
    VDEC_EX_V2_StreamId*    StreamID;
    void* pRet;
    void* param[1];  // at most 8 param
}VDEC_EX_V2_IO_Param_1;

typedef struct DLL_PACKED
{
    VDEC_EX_V2_User_Cmd     eUserCmd;
    VDEC_EX_V2_StreamId*    StreamID;
    void* pRet;
    void* param[2];  // at most 8 param
}VDEC_EX_V2_IO_Param_2;

typedef struct DLL_PACKED
{
    VDEC_EX_V2_User_Cmd     eUserCmd;
    VDEC_EX_V2_StreamId*    StreamID;
    void* pRet;
    void* param[3];  // at most 8 param
}VDEC_EX_V2_IO_Param_3;

typedef struct DLL_PACKED
{
    VDEC_EX_V2_User_Cmd     eUserCmd;
    VDEC_EX_V2_StreamId*    StreamID;
    void* pRet;
    void* param[4];  // at most 8 param
}VDEC_EX_V2_IO_Param_4;


typedef struct DLL_PACKED
{
    VDEC_EX_IapGnBufShareBWMode* pVDEC_EX_IapGnBufShareBWMode;
} VDEC_EX_PtrIapGnBufShareBWMode;

typedef struct DLL_PACKED
{
    VDEC_EX_DecModCfg* pVDEC_EX_DecModCfg;
} VDEC_EX_PtrDecModCfg;

typedef struct DLL_PACKED
{
    VDEC_Framebuffer_Ctrl* pVDEC_Framebuffer_Ctrl;
} VDEC_PtrFramebuffer_Ctrl;

//E_VDEC_EX_V2_USER_CMD_SET_TOTALRANGE_BITSTREAMBUFFER
typedef struct DLL_PACKED
{
    VDEC_EX_TotalBufRange* pVDEC_EX_TotalBufRange;
} VDEC_EX_PtrTotalBufRange;

typedef struct DLL_PACKED
{
    VDEC_EX_FRC_OutputParam* pVDEC_EX_FRC_OutputParam;
} VDEC_EX_PtrFRC_OutputParam;

typedef struct DLL_PACKED
{
    VDEC_EX_Err_Tolerance* pVDEC_EX_Err_Tolerance;
} VDEC_EX_PtrErr_Tolerance;

typedef struct DLL_PACKED
{
    VDEC_EX_Decode_Timeout_Param* pVDEC_EX_Decode_Timeout_Param;
} VDEC_EX_PtrTIMEOUT_PARAM;

//E_VDEC_EX_V2_USER_CMD_SET_DYNAMIC_DISP_PATH
typedef struct DLL_PACKED
{
    VDEC_EX_DynmcDispPath* pVDEC_EX_DynmcDispPath;
} VDEC_EX_PtrDynmcDispPath;

#ifdef CONFIG_COMPAT
typedef struct
{
    compat_uint_t   eUserCmd;
    compat_uptr_t   StreamID;
    compat_uptr_t   pRet;
    compat_uptr_t   param[8];
}VDEC_EX_V2_IO_Param_32;
#endif

//E_VDEC_EX_V2_CMD_GET_FREE_STREAM_ID
UADP_SDT_NAMEn_DEF(VDEC_EX_STREAM_V2_ID,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_STREAM_ID,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_STREAM_TYPE,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_CODEC_TYPE,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_GET_FREE_STREAM_ID,6);
//E_VDEC_EX_V2_CMD_INIT
UADP_SDT_NAMEn_DEF(VDEC_EX_INIT_PARAM,6);
UADP_SDT_NAMEn_DEF(VDEC_EX_INIT,3);
//E_VDEC_EX_V2_CMD_SET_CONTROL
//E_VDEC_EX_V2_USER_CMD_CHECK_DISPINFO_READY:
//E_VDEC_EX_V2_USER_CMD_PLAY:
//E_VDEC_EX_V2_USER_CMD_PAUSE:
//E_VDEC_EX_V2_USER_CMD_RESUME:
//E_VDEC_EX_V2_USER_CMD_STEP_DISP:
//E_VDEC_EX_V2_USER_CMD_STEP_DECODE:
//E_VDEC_EX_V2_USER_CMD_FIRE_DEC:
//E_VDEC_EX_V2_USER_CMD_MHEG_RST_IFRAME_DEC:
//E_VDEC_EX_V2_USER_CMD_CC_STOP_PARSING:
//E_VDEC_EX_V2_USER_CMD_RST:
//E_VDEC_EX_V2_USER_CMD_EXIT:
UADP_SDT_NAMEn_DEF(VDEC_EX_IO,2);
//E_VDEC_EX_V2_USER_CMD_SET_FRC_MODE
UADP_SDT_NAMEn_DEF(VDEC_EX_FRC_MODE,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_SET_FRC_MODE,3);
//E_VDEC_EX_V2_USER_CMD_SET_DYNSCALING_PARAMS

UADP_SDT_NAMEn_DEF(VDEC_EX_SET_DYNSCALING_PARAMS,4);
//E_VDEC_EX_V2_USER_CMD_SET_DBG_LEVEL
UADP_SDT_NAMEn_DEF(VDEC_EX_DBG_LEVEL,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_SET_DBG_LEVEL,3);
//E_VDEC_EX_V2_USER_CMD_SET_TRICK_MODE
UADP_SDT_NAMEn_DEF(VDEC_EX_TRICK_DEC,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_SET_TRICK_MODE,3);
//E_VDEC_EX_V2_USER_CMD_PUSH_DECQ
UADP_SDT_NAMEn_DEF(VDEC_EX_DEC_CMD,1);
UADP_SDT_NAMEn_DEF(VDEC_EX_PUSH_DECQ,3);
//E_VDEC_EX_V2_USER_CMD_FLUSH
UADP_SDT_NAMEn_DEF(VDEC_EX_FREEZE_PIC_SELECT,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_FLUSH,3);
//E_VDEC_EX_V2_USER_CMD_ENABLE_LAST_FRAME_SHOW:
//E_VDEC_EX_V2_USER_CMD_SET_FREEZE_DISP:
//E_VDEC_EX_V2_USER_CMD_SET_BLUE_SCREEN:
//E_VDEC_EX_V2_USER_CMD_DISABLE_DEBLOCKING:
//E_VDEC_EX_V2_USER_CMD_DISABLE_QUARTER_PIXEL:
//E_VDEC_EX_V2_USER_CMD_SET_AUTO_RM_LST_ZERO_BYTE:
//E_VDEC_EX_V2_USER_CMD_SET_BLOCK_DISPLAY:
//E_VDEC_EX_V2_USER_CMD_ENABLE_ES_BUFF_MALLOC:
UADP_SDT_NAMEn_DEF(VDEC_EX_BOOL,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_IO_BOOL,3);
//E_VDEC_EX_V2_USER_CMD_SET_SPEED
UADP_SDT_NAMEn_DEF(VDEC_EX_SPEED_TYPE,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_SPEED,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_SET_SPEED,4);
//E_VDEC_EX_V2_USER_CMD_RESET_PTS:
//E_VDEC_EX_V2_USER_CMD_AVSYNC_FREERUN_THRESHOLD:
//E_VDEC_EX_V2_USER_CMD_SEEK_TO_PTS:
//E_VDEC_EX_V2_USER_CMD_SKIP_TO_PTS:// TODO: what's the difference between skip & seek?
//E_VDEC_EX_V2_USER_CMD_CC_INIT;
UADP_SDT_NAMEn_DEF(VDEC_EX_MS_U32,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_IO_U32,3);
//E_VDEC_EX_V2_USER_CMD_AVSYNC_ON
UADP_SDT_NAMEn_DEF(VDEC_EX_MS_U16,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_AVSYNC_ON,5);
//E_VDEC_EX_V2_USER_CMD_UNSET_EVENT_MULTICALLBACK
UADP_SDT_NAMEn_DEF(VDEC_EX_TYPE,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_UNSET_EVENT_MULTICALLBACK,6);
//E_VDEC_EX_V2_USER_CMD_SET_BALANCE_BW
UADP_SDT_NAMEn_DEF(VDEC_EX_SET_BALANCE_BW,6);
//E_VDEC_EX_V2_USER_CMD_GEN_PATTERN
UADP_SDT_NAMEn_DEF(VDEC_EX_PATTERN_TYPE,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_GEN_PATTERN,5);
//E_VDEC_EX_V2_USER_CMD_MHEG_DECODE_IFRAME:
UADP_SDT_NAMEn_DEF(VDEC_EX_MHEG_DECODE_IFRAME,5);
//E_VDEC_EX_V2_USER_CMD_CC_START_PARSING:
UADP_SDT_NAMEn_DEF(VDEC_EX_CC_CONFIG,1);
UADP_SDT_NAMEn_DEF(VDEC_EX_CC_START_PARSING,3);
//E_VDEC_EX_V2_USER_CMD_DISPLAY_FRAME:
//UADP_SDT_NAMEn_DEF(VDEC_EX_DISP_FRAME,2);
UADP_SDT_NAMEn_DEF(VDEC_EX_DISP_FRAME,0);

UADP_SDT_NAMEn_DEF(VDEC_EX_DISP_RELEASE_FRAME,3);
//E_VDEC_EX_V2_USER_CMD_CAPTURE_FRAME
UADP_SDT_NAMEn_DEF(VDEC_EX_CAPTURE_FRAME,4);
//E_VDEC_EX_V2_USER_CMD_CC_SET_CFG:
UADP_SDT_NAMEn_DEF(VDEC_EX_CC_FORMAT,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_CC_TYPE,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_CC_INPUT_PARAM,1);
UADP_SDT_NAMEn_DEF(VDEC_EX_CC_SET_CFG,5);
//E_VDEC_EX_V2_USER_CMD_CC_SET_BUFF_START_ADDR
//E_VDEC_EX_V2_USER_CMD_CC_UPDATE_WRITE_ADDR:
//E_VDEC_EX_V2_USER_CMD_CC_UPDATE_READ_ADDR:
UADP_SDT_NAMEn_DEF(VDEC_EX_CC_UPDATE_ADDR,4);
//E_VDEC_EX_V2_USER_CMD_CC_DISABLE_PARSING:
//E_VDEC_EX_V2_USER_CMD_CC_GET_IS_RST_DONE
UADP_SDT_NAMEn_DEF(VDEC_EX_CC_IO_CC_FORMAT,3);
//E_VDEC_EX_V2_USER_CMD_GETLIBVER:
UADP_SDT_NAMEn_DEF(VDEC_EX_MSIF_VERSION,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_GET_LIBVER,3);
//E_VDEC_EX_V2_USER_CMD_GETINFO:
UADP_SDT_NAMEn_DEF(VDEC_EX_INFO,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_GET_INFO,3);
//E_VDEC_EX_V2_USER_CMD_CHECKCAPS
UADP_SDT_NAMEn_DEF(VDEC_EX_CHECK_CAPS,4);
//E_VDEC_EX_V2_USER_CMD_GET_DISP_INFO:
UADP_SDT_NAMEn_DEF(VDEC_EX_DISP_INFO,1);
UADP_SDT_NAMEn_DEF(VDEC_EX_GET_DISP_INFO,3);
//E_VDEC_EX_V2_USER_CMD_GET_EXT_DISP_INFO
UADP_SDT_NAMEn_DEF(VDEC_EX_EXT_DISP_INFO,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_GET_EXT_DISP_INFO,3);
//E_VDEC_EX_V2_USER_CMD_GET_DEC_FRAME_INFO
//UADP_SDT_NAMEn_DEF(VDEC_EX_FRAME_INFO,2);
UADP_SDT_NAMEn_DEF(VDEC_EX_FRAME_INFO,0);

UADP_SDT_NAMEn_DEF(VDEC_EX_GET_DEC_FRAME_INFO,3);
//E_VDEC_EX_V2_USER_CMD_GET_DEC_TIMECODE
UADP_SDT_NAMEn_DEF(VDEC_EX_TIME_CODE,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_GET_DEC_TIMECODE,3);

//E_VDEC_EX_V2_USER_CMD_GET_COLOUR_PRIMARIES
UADP_SDT_NAMEn_DEF(VDEC_EX_MS_U8,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_IO_U8,3);
UADP_SDT_NAMEn_DEF(VDEC_EX_GET_COLOUR_PRIMARIES,3);
//E_VDEC_EX_V2_USER_CMD_GET_FW_VERSION
UADP_SDT_NAMEn_DEF(VDEC_EX_FW_TYPE,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_GET_FW_VERSION,4);
//E_VDEC_EX_V2_USER_CMD_GET_VIDEO_PTS_STC_DELTA
UADP_SDT_NAMEn_DEF(VDEC_EX_MS_U64,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_SET_GET_U64,3);
//E_VDEC_EX_V2_USER_CMD_GET_ERR_CODE
UADP_SDT_NAMEn_DEF(VDEC_EX_ERR_CODE,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_GET_ERR_CODE,3);
//E_VDEC_EX_V2_USER_CMD_GET_CC_INFO
UADP_SDT_NAMEn_DEF(VDEC_EX_CC_INFO,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_GET_CC_INFO,4);
//E_VDEC_EX_V2_USER_CMD_GET_ACTIVE_CODEC_TYPE
UADP_SDT_NAMEn_DEF(VDEC_EX_GET_ACTIVE_CODEC_TYPE,3);
//E_VDEC_EX_V2_USER_CMD_GET_PATTERN_LEAST_LENGTH
UADP_SDT_NAMEn_DEF(VDEC_EX_GET_PATTERN_LEAST_LENGTH,4);
//E_VDEC_EX_V2_USER_CMD_GET_ES_BUFF
UADP_SDT_NAMEn_DEF(VDEC_EX_GET_ES_BUFF,5);
//E_VDEC_EX_V2_USER_CMD_CC_GET_INFO
UADP_SDT_NAMEn_DEF(VDEC_EX_CC_INFO_CMD,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_CC_GET_INFO,5);
//E_VDEC_EX_V2_USER_CMD_CC_GET_WRITE_ADDR
UADP_SDT_NAMEn_DEF(VDEC_EX_GET_CC_GET_RW_ADDR,4);
//E_VDEC_EX_V2_USER_CMD_FRC_OUTPUT
UADP_SDT_NAMEn_DEF(VDEC_EX_FRC_OUTPUT_PARAM,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_PTR_FRC_OUTPUT_PARAM,1);
UADP_SDT_NAMEn_DEF(VDEC_EX_FRC_OUTPUT,3);

//E_VDEC_EX_V2_USER_CMD_UT_SET_DBG_MODE
UADP_SDT_NAMEn_DEF(VDEC_EX_DBG_MODE,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_UT_SET_DBG_MODE,3);
//E_VDEC_EX_V2_USER_CMD_FIELD_POLARITY_DISPLAY_ONE_FIELD
UADP_SDT_NAMEn_DEF(VDEC_EX_FIELD_POLARITY,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_FIELD_POLARITY_DISPLAY_ONE_FIELD,3);
//E_VDEC_EX_V2_USER_CMD_SET_EXTERNAL_DS_BUFFER
UADP_SDT_NAMEn_DEF(VDEC_EX_EXTERNAL_DS_BUF,1);
UADP_SDT_NAMEn_DEF(VDEC_EX_SET_EXTERNAL_DS_BUFFER,3);
//E_VDEC_EX_V2_USER_CMD_ENABLE_DECODE_ENGINE_TIMEOUT
UADP_SDT_NAMEn_DEF(VDEC_EX_TIMEOUT_PARAM,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_PTR_TIMEOUT_PARAM,1);
UADP_SDT_NAMEn_DEF(VDEC_EX_ENABLE_DECODE_ENGINE_TIMEOUT,3);
//E_VDEC_EX_V2_USER_CMD_SET_ERROR_TOLERANCE
UADP_SDT_NAMEn_DEF(VDEC_EX_ERR_TOLERANCE,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_PTR_ERR_TOLERANCE,1);
UADP_SDT_NAMEn_DEF(VDEC_EX_SET_ERROR_TOLERANCE,3);
//E_VDEC_EX_V2_USER_CMD_GET_MAIN_STREAM_ID
UADP_SDT_NAMEn_DEF(VDEC_EX_GET_STREAM_ID,3);
//E_VDEC_EX_V2_USER_CMD_GET_FPA_SEI
UADP_SDT_NAMEn_DEF(VDEC_EX_FRAME_PACKING_SIE,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_GET_FPA_SEI,3);
//E_VDEC_EX_V2_USER_CMD_GET_FPA_SEI_EX
UADP_SDT_NAMEn_DEF(VDEC_EX_VER_CTRL,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_GET_FPA_SEI_EX,3);
//E_VDEC_EX_V2_USER_CMD_GET_CRC_VALUE
UADP_SDT_NAMEn_DEF(VDEC_EX_CRC_VALUE,2);
UADP_SDT_NAMEn_DEF(VDEC_EX_GET_CRC_VALUE,3);
//E_VDEC_EX_V2_USER_CMD_GET_FRAME_INFO_EX:
//UADP_SDT_NAMEn_DEF(VDEC_EX_FRAME_INFO_EX,4);
UADP_SDT_NAMEn_DEF(VDEC_EX_FRAME_INFO_EX,0);

UADP_SDT_NAMEn_DEF(VDEC_EX_GET_FRAME_INFO_EX,3);
//E_VDEC_EX_V2_USER_CMD_GET_NEXT_DISP_FRAME_INFO_EXT:
UADP_SDT_NAMEn_DEF(VDEC_EX_FRAME_INFO_EXT,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_GET_FRAME_INFO_EXT,3);

UADP_SDT_NAMEn_DEF(VDEC_EX_FRAME_INFO_V0,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_GET_FRAME_INFO_V0,3);
#ifdef VDEC_CAP_HEVC_HDR_V2
UADP_SDT_NAMEn_DEF(VDEC_EX_FRAME_INFO_V2,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_GET_FRAME_INFO_V2,3);
#endif

#ifdef VDEC_CAP_HEVC_HDR_V3
UADP_SDT_NAMEn_DEF(VDEC_EX_FRAME_INFO_V3,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_GET_FRAME_INFO_V3,3);
#endif

#ifdef VDEC_CAP_FRAME_INFO_EXT_V4
UADP_SDT_NAMEn_DEF(VDEC_EX_FRAME_INFO_V4,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_GET_FRAME_INFO_V4,3);
#endif

#ifdef VDEC_CAP_FRAME_INFO_EXT_V5
UADP_SDT_NAMEn_DEF(VDEC_EX_FRAME_INFO_V5,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_GET_FRAME_INFO_V5,3);
#endif

#ifdef VDEC_CAP_FRAME_INFO_EXT_V6
UADP_SDT_NAMEn_DEF(VDEC_EX_FRAME_INFO_V6,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_GET_FRAME_INFO_V6,3);
#endif

//E_VDEC_EX_V2_USER_CMD_PREGETSTATUS
UADP_SDT_NAMEn_DEF(VDEC_EX_STATUS,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_PREGETSTATUS,3);
//E_VDEC_EX_V2_USER_CMD_SYSTEM_PRESET_VPU_CLOCK
UADP_SDT_NAMEn_DEF(VDEC_EX_CLOCK_SPEED,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_SYSTEM_PRESET_CLOCK,3);
//E_VDEC_EX_V2_USER_CMD_SETPOWERSTATE
UADP_SDT_NAMEn_DEF(VDEC_EX_POWER_MODE,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_SET_POWERSTATE,3);

//E_VDEC_EX_V2_USER_CMD_PRESET_DECODE_MODE
UADP_SDT_NAMEn_DEF(VDEC_EX_DEC_MOD_CFG,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_PTR_DEC_MOD_CFG,1);
UADP_SDT_NAMEn_DEF(VDEC_EX_PRESET_DECODE_MODE,3);

//E_VDEC_EX_V2_USER_CMD_HVD_IAPGN_BUF_SHARE_BW_MODE
UADP_SDT_NAMEn_DEF(VDEC_EX_IAP_GnBufShareBWMode,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_PTR_IAP_GnBufShareBWMode,1);
UADP_SDT_NAMEn_DEF(VDEC_EX_HVD_IAPGN_BUF_SHARE_BW_MODE,3);

//E_VDEC_EX_V2_USER_CMD_GET_EVENT_FLAG
UADP_SDT_NAMEn_DEF(VDEC_EX_GET_EVENT_FLAG,4);

//E_VDEC_EX_V2_USER_CMD_SET_FRAMEBUFF2
UADP_SDT_NAMEn_DEF(VDEC_EX_FRAMEBUFF,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_SET_FRAMEBUFF2,4);

//E_VDEC_EX_V2_USER_CMD_SET_TRICKPLAY_2X_MODE
UADP_SDT_NAMEn_DEF(VDEC_EX_TRICKPLAY_2X_MODE,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_SET_TRICKPLAY_2X_MODE,3);

//E_VDEC_EX_V2_USER_CMD_GET_DCV_SEI
UADP_SDT_NAMEn_DEF(VDEC_EX_DCV_SEI,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_GET_DCV_SEI,3);

//E_VDEC_EX_V2_USER_CMD_GET_VUI_DISP_INFO
UADP_SDT_NAMEn_DEF(VDEC_EX_VUI_DISP_INFO,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_GET_VUI_DISP_INFO,3);

//E_VDEC_EX_V2_USER_CMD_AUTO_ARRANGE_FRAMEBUFFER_USAGE
UADP_SDT_NAMEn_DEF(VDEC_EX_FRAMEBUFFER_CTRL,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_PTR_FRAMEBUFFER_CTRL,1);
UADP_SDT_NAMEn_DEF(VDEC_EX_AUTO_ARRANGE_FRAMEBUFFER_USAGE,3);

//E_VDEC_EX_V2_USER_CMD_MFCODEC_MODE
UADP_SDT_NAMEn_DEF(VDEC_EX_MFCODEC_MODE,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_SET_MFCODEC_MODE,3);

//E_VDEC_EX_V2_USER_CMD_VDEC_FEATURE
UADP_SDT_NAMEn_DEF(VDEC_EX_VDEC_FEATURE,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_SET_VDEC_FEATURE,3);

//E_VDEC_EX_V2_USER_CMD_SET_DISPLAY_MODE
UADP_SDT_NAMEn_DEF(VDEC_EX_DISPLAYMODE,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_SET_DISPLAYMODE,3);

//E_VDEC_EX_V2_USER_CMD_PRESET_STC
UADP_SDT_NAMEn_DEF(VDEC_EX_STC,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_PRESET_STC,3);


//E_VDEC_EX_V2_USER_CMD_SET_TOTALRANGE_BITSTREAMBUFFER
UADP_SDT_NAMEn_DEF(VDEC_EX_TOTALRANGE_BITSTREAMBUFFER,1);
UADP_SDT_NAMEn_DEF(VDEC_EX_PTR_TOTALRANGE_BITSTREAMBUFFER,1);
UADP_SDT_NAMEn_DEF(VDEC_EX_SET_TOTALRANGE_BITSTREAMBUFFER,3);

//E_VDEC_EX_V2_USER_CMD_GET_BUFFER_INFO
UADP_SDT_NAMEn_DEF(VDEC_EX_BUFFER_INFO,1);
//UADP_SDT_NAMEn_DEF(VDEC_EX_BUFFER_INFO,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_GET_BUFFER_INFO,3);

//E_VDEC_EX_V2_USER_CMD_SET_DYNAMIC_DISP_PATH
UADP_SDT_NAMEn_DEF(VDEC_EX_DYNAMIC_DISP_PATH,0);
UADP_SDT_NAMEn_DEF(VDEC_EX_PTR_DYNAMIC_DISP_PATH,1);
UADP_SDT_NAMEn_DEF(VDEC_EX_SET_DYNAMIC_DISP_PATH,3);

//MS_PHYADDR
UADP_SDT_NAMEn_DEF(VDEC_EX_MS_PHYADDR,0);
//MS_VIRT
UADP_SDT_NAMEn_DEF(VDEC_EX_MS_VIRT,0);
//long
UADP_SDT_NAMEn_DEF(VDEC_EX_MS_LONG,0);
//MS_SIZE
UADP_SDT_NAMEn_DEF(VDEC_EX_MS_SIZE,0);
//MS_PHY
UADP_SDT_NAMEn_DEF(VDEC_EX_MS_PHY,0);





MS_U32 VDEC_EX_adp_Init(FUtopiaIOctl* pIoctl)
{
    UADP_SDT_NAME0(VDEC_EX_MS_PHYADDR,MS_PHYADDR);
    UADP_SDT_NAME0(VDEC_EX_MS_VIRT,MS_VIRT);
    UADP_SDT_NAME0(VDEC_EX_MS_LONG,long);
    UADP_SDT_NAME0(VDEC_EX_MS_SIZE,MS_SIZE);
    UADP_SDT_NAME0(VDEC_EX_MS_PHY,MS_PHY);


    UADP_SDT_NAME0(VDEC_EX_STREAM_V2_ID,VDEC_EX_V2_StreamId);
    UADP_SDT_NAME0(VDEC_EX_STREAM_ID,VDEC_StreamId);
    UADP_SDT_NAME0(VDEC_EX_STREAM_TYPE,VDEC_EX_Stream);
    UADP_SDT_NAME0(VDEC_EX_CODEC_TYPE,VDEC_EX_CodecType);

    UADP_SDT_NAME0(VDEC_EX_FRC_MODE,VDEC_EX_FrcMode);

    UADP_SDT_NAME0(VDEC_EX_DBG_LEVEL,VDEC_EX_DbgLevel);
    UADP_SDT_NAME0(VDEC_EX_TRICK_DEC,VDEC_EX_TrickDec);

    UADP_SDT_NAME0(VDEC_EX_FREEZE_PIC_SELECT,VDEC_EX_FreezePicSelect);
    UADP_SDT_NAME0(VDEC_EX_BOOL,MS_BOOL);
    UADP_SDT_NAME0(VDEC_EX_SPEED_TYPE,VDEC_EX_SpeedType);
    UADP_SDT_NAME0(VDEC_EX_SPEED,VDEC_EX_DispSpeed);
    UADP_SDT_NAME0(VDEC_EX_MS_U32,MS_U32);
    UADP_SDT_NAME0(VDEC_EX_MS_U16,MS_U16);
    UADP_SDT_NAME0(VDEC_EX_TYPE,VDEC_EX_CB_TYPE);
    UADP_SDT_NAME0(VDEC_EX_PATTERN_TYPE,VDEC_EX_PatternType);

    UADP_SDT_NAME1(VDEC_EX_TOTALRANGE_BITSTREAMBUFFER,VDEC_EX_TotalBufRange,UADP_SDT_AT,szTotalBufSize,VDEC_EX_MS_SIZE);
    UADP_SDT_NAME1(VDEC_EX_PTR_TOTALRANGE_BITSTREAMBUFFER,VDEC_EX_PtrTotalBufRange,UADP_SDT_P2N ,pVDEC_EX_TotalBufRange,VDEC_EX_TOTALRANGE_BITSTREAMBUFFER);
    UADP_SDT_NAME3(VDEC_EX_SET_TOTALRANGE_BITSTREAMBUFFER,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_PTR_TOTALRANGE_BITSTREAMBUFFER);

    //================================================================
    //UADP_SPT_BGN(& spt_VDEC_EX_DISP_FRAME  [0],sizeof(VDEC_EX_DispFrame));
    //UADPBypassSetSPT(& spt_VDEC_EX_DISP_FRAME [1],  UADP_SDT_AT,  ((unsigned long) &((VDEC_EX_DispFrame *)0)->stFrmInfo.u32LumaAddr), (unsigned long)spt_VDEC_EX_MS_PHY);
    //UADPBypassSetSPT(& spt_VDEC_EX_DISP_FRAME [2],  UADP_SDT_AT,  ((unsigned long) &((VDEC_EX_DispFrame *)0)->stFrmInfo.u32ChromaAddr), (unsigned long)spt_VDEC_EX_MS_PHY);
    //UADP_SPT_FIN(& spt_VDEC_EX_DISP_FRAME  [3]);
    UADP_SDT_NAME0(VDEC_EX_DISP_FRAME,VDEC_EX_DispFrame);// TODO: remove MS_PHY
    //================================================================
    UADP_SDT_NAME0(VDEC_EX_CC_FORMAT,VDEC_EX_CCFormat);
    UADP_SDT_NAME0(VDEC_EX_CC_TYPE,VDEC_EX_CCType);

    UADP_SDT_NAME0(VDEC_EX_MSIF_VERSION,MSIF_Version);
    //UADP_SDT_NAME0(VDEC_EX_INFO,VDEC_EX_Info);

    UADP_SDT_NAME0(VDEC_EX_EXT_DISP_INFO,VDEC_EX_ExtDispInfo);

    //================================================================
    //UADP_SDT_NAME2(VDEC_EX_FRAME_INFO,VDEC_EX_FrameInfo,UADP_SDT_AT, u32LumaAddr,VDEC_EX_MS_PHY, UADP_SDT_AT,u32ChromaAddr, VDEC_EX_MS_PHY);
    UADP_SDT_NAME0(VDEC_EX_FRAME_INFO,VDEC_EX_FrameInfo);// TODO: remove MS_PHY
    //================================================================
    UADP_SDT_NAME0(VDEC_EX_TIME_CODE,VDEC_EX_TimeCode);
    UADP_SDT_NAME0(VDEC_EX_MS_U8,MS_U8);
    UADP_SDT_NAME0(VDEC_EX_FW_TYPE,VDEC_EX_FwType);
    UADP_SDT_NAME0(VDEC_EX_MS_U64,MS_U64);
    UADP_SDT_NAME0(VDEC_EX_ERR_CODE,VDEC_EX_ErrCode);
    UADP_SDT_NAME0(VDEC_EX_CC_INFO,VDEC_EX_CC_Info);
    UADP_SDT_NAME0(VDEC_EX_CC_INFO_CMD,VDEC_EX_CCInfoCmd);
    UADP_SDT_NAME0(VDEC_EX_FRC_OUTPUT_PARAM,VDEC_EX_FRC_OutputParam);
    UADP_SDT_NAME0(VDEC_EX_DBG_MODE,VDEC_EX_DbgMode);
    UADP_SDT_NAME0(VDEC_EX_FIELD_POLARITY,VDEC_EX_Field_Polarity);

    UADP_SDT_NAME0(VDEC_EX_TIMEOUT_PARAM,VDEC_EX_Decode_Timeout_Param);
//    UADP_SDT_NAME0(VDEC_EX_ERR_TOLERANCE,VDEC_EX_Err_Tolerance);
    UADP_SDT_NAME0(VDEC_EX_FRAME_PACKING_SIE,VDEC_EX_Frame_packing_SEI);
    UADP_SDT_NAME0(VDEC_EX_VER_CTRL,VDEC_EX_Frame_packing_SEI_EX);

    //=================================================================
    UADP_SPT_BGN(& spt_VDEC_EX_CRC_VALUE  [0],sizeof(VDEC_EX_CrcValue));
    UADPBypassSetSPT(& spt_VDEC_EX_CRC_VALUE [1],  UADP_SDT_AT,  ((unsigned long) &((VDEC_EX_CrcValue *)0)->stCrcIn.u32LumaStartAddr), (unsigned long)spt_VDEC_EX_MS_VIRT);
    UADPBypassSetSPT(& spt_VDEC_EX_CRC_VALUE [2],  UADP_SDT_AT,  ((unsigned long) &((VDEC_EX_CrcValue *)0)->stCrcIn.u32ChromaStartAddr), (unsigned long)spt_VDEC_EX_MS_VIRT);
    UADP_SPT_FIN(& spt_VDEC_EX_CRC_VALUE  [3]);
    //=================================================================

    //=================================================================
    //UADP_SPT_BGN(& spt_VDEC_EX_FRAME_INFO_EX  [0],sizeof(VDEC_EX_FrameInfoEX));
    //UADPBypassSetSPT(& spt_VDEC_EX_FRAME_INFO_EX [1],  UADP_SDT_AT,  ((unsigned long) &((VDEC_EX_FrameInfoEX *)0)->sFrameInfo.u32LumaAddr), (unsigned long)spt_VDEC_EX_MS_PHY);
    //UADPBypassSetSPT(& spt_VDEC_EX_FRAME_INFO_EX [2],  UADP_SDT_AT,  ((unsigned long) &((VDEC_EX_FrameInfoEX *)0)->sFrameInfo.u32ChromaAddr), (unsigned long)spt_VDEC_EX_MS_PHY);
    //UADPBypassSetSPT(& spt_VDEC_EX_FRAME_INFO_EX [3],  UADP_SDT_AT,  ((unsigned long) &((VDEC_EX_FrameInfoEX *)0)->u32LumaAddr_2bit), (unsigned long)spt_VDEC_EX_MS_PHY);
    //UADPBypassSetSPT(& spt_VDEC_EX_FRAME_INFO_EX [4],  UADP_SDT_AT,  ((unsigned long) &((VDEC_EX_FrameInfoEX *)0)->u32ChromaAddr_2bit), (unsigned long)spt_VDEC_EX_MS_PHY);
    //UADP_SPT_FIN(& spt_VDEC_EX_FRAME_INFO_EX  [5]);
    UADP_SDT_NAME0(VDEC_EX_FRAME_INFO_EX,VDEC_EX_FrameInfoEX);// TODO: remove MS_PHY
    //=================================================================
    UADP_SDT_NAME0(VDEC_EX_STATUS,VDEC_EX_Status);
    UADP_SDT_NAME0(VDEC_EX_CLOCK_SPEED,VDEC_EX_ClockSpeed);
    UADP_SDT_NAME0(VDEC_EX_POWER_MODE,EN_POWER_MODE);
    UADP_SDT_NAME0(VDEC_EX_DEC_MOD_CFG,VDEC_EX_DecModCfg);
    UADP_SDT_NAME0(VDEC_EX_IAP_GnBufShareBWMode,VDEC_EX_IapGnBufShareBWMode);

    UADP_SDT_NAME0(VDEC_EX_FRAME_INFO_EXT,VDEC_EX_FrameInfoExt);
    #ifdef VDEC_CAP_FRAME_INFO_EXT_V6
        UADP_SDT_NAME0(VDEC_EX_FRAME_INFO_V6,VDEC_EX_FrameInfoExt_v6);
    #endif
    #ifdef VDEC_CAP_FRAME_INFO_EXT_V5
        UADP_SDT_NAME0(VDEC_EX_FRAME_INFO_V5,VDEC_EX_FrameInfoExt_v5);
    #endif
    #ifdef VDEC_CAP_FRAME_INFO_EXT_V4
        UADP_SDT_NAME0(VDEC_EX_FRAME_INFO_V4,VDEC_EX_FrameInfoExt_v4);
    #endif
    #ifdef VDEC_CAP_HEVC_HDR_V3
        UADP_SDT_NAME0(VDEC_EX_FRAME_INFO_V3,VDEC_EX_FrameInfoExt_v3);
    #endif
    #ifdef VDEC_CAP_HEVC_HDR_V2
        UADP_SDT_NAME0(VDEC_EX_FRAME_INFO_V2,VDEC_EX_FrameInfoExt_v2);
    #endif
        UADP_SDT_NAME0(VDEC_EX_FRAME_INFO_V0,VDEC_EX_FrameInfoExt_version0);

    UADP_SDT_NAME1(VDEC_EX_DEC_CMD,VDEC_EX_DecCmd,  UADP_SDT_AT , u32StAddr , VDEC_EX_MS_VIRT);
    UADP_SDT_NAME1(VDEC_EX_CC_INPUT_PARAM,VDEC_EX_CC_InputPara ,UADP_SDT_AT, u32Val, VDEC_EX_MS_VIRT);
    UADP_SDT_NAME1(VDEC_EX_DISP_INFO,VDEC_EX_DispInfo,UADP_SDT_AT , u32DynScalingAddr, VDEC_EX_MS_VIRT);
    UADP_SDT_NAME1(VDEC_EX_EXTERNAL_DS_BUF,VDEC_EX_EXTERNAL_DS_BUFFER, UADP_SDT_AT,u32DSBufAddr,VDEC_EX_MS_VIRT );
    UADP_SDT_NAME1(VDEC_EX_CC_CONFIG,VDEC_EX_CCCfg,UADP_SDT_AT,u32BufStAdd,VDEC_EX_MS_VIRT);

    //E_VDEC_EX_V2_CMD_GET_FREE_STREAM_ID
    UADP_SDT_NAME6(VDEC_EX_GET_FREE_STREAM_ID,VDEC_EX_V2_IO_Param_4,UADP_SDT_P2N,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N,param[0],VDEC_EX_STREAM_ID,UADP_SDT_P2N,param[1],VDEC_EX_MS_U32,UADP_SDT_P2N,param[2],VDEC_EX_STREAM_TYPE,UADP_SDT_P2N,param[3],VDEC_EX_CODEC_TYPE);
    //E_VDEC_EX_V2_CMD_INIT
    //=======================================
    UADP_SPT_BGN(& spt_VDEC_EX_INIT_PARAM  [0],sizeof(VDEC_EX_InitParam));

    UADPBypassSetSPT(& spt_VDEC_EX_INIT_PARAM [1], UADP_SDT_AT,((unsigned long) &((VDEC_EX_InitParam *)0)->SysConfig.u32FWBinarySize), (unsigned long)spt_VDEC_EX_MS_SIZE);
    UADPBypassSetSPT(& spt_VDEC_EX_INIT_PARAM [2], UADP_SDT_AT,((unsigned long) &((VDEC_EX_InitParam *)0)->SysConfig.u32CodeBufSize), (unsigned long)spt_VDEC_EX_MS_SIZE);
    UADPBypassSetSPT(& spt_VDEC_EX_INIT_PARAM [3], UADP_SDT_AT,((unsigned long) &((VDEC_EX_InitParam *)0)->SysConfig.u32FrameBufSize), (unsigned long)spt_VDEC_EX_MS_SIZE);
    UADPBypassSetSPT(& spt_VDEC_EX_INIT_PARAM [4], UADP_SDT_AT,((unsigned long) &((VDEC_EX_InitParam *)0)->SysConfig.u32BitstreamBufSize), (unsigned long)spt_VDEC_EX_MS_SIZE);
    UADPBypassSetSPT(& spt_VDEC_EX_INIT_PARAM [5], UADP_SDT_AT,((unsigned long) &((VDEC_EX_InitParam *)0)->SysConfig.u32DrvProcBufSize), (unsigned long)spt_VDEC_EX_MS_SIZE);
    UADPBypassSetSPT(& spt_VDEC_EX_INIT_PARAM [6], UADP_SDT_AT,((unsigned long) &((VDEC_EX_InitParam *)0)->SysConfig.u32VlcTabBinarySize), (unsigned long)spt_VDEC_EX_MS_SIZE);

    UADP_SPT_FIN(& spt_VDEC_EX_INIT_PARAM  [7]);

    UADP_SDT_NAME3(VDEC_EX_INIT,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_INIT_PARAM);
    //=======================================
    //E_VDEC_EX_V2_CMD_SET_CONTROL
    //E_VDEC_EX_V2_USER_CMD_CHECK_DISPINFO_READY:
    //E_VDEC_EX_V2_USER_CMD_PLAY:
    //E_VDEC_EX_V2_USER_CMD_PAUSE:
    //E_VDEC_EX_V2_USER_CMD_RESUME:
    //E_VDEC_EX_V2_USER_CMD_STEP_DISP:
    //E_VDEC_EX_V2_USER_CMD_STEP_DECODE:
    //E_VDEC_EX_V2_USER_CMD_FIRE_DEC:
    //E_VDEC_EX_V2_USER_CMD_MHEG_RST_IFRAME_DEC:
    //E_VDEC_EX_V2_USER_CMD_CC_STOP_PARSING:
    //E_VDEC_EX_V2_USER_CMD_RST:
    //E_VDEC_EX_V2_USER_CMD_EXIT:
    UADP_SDT_NAME2(VDEC_EX_IO,VDEC_EX_V2_IO_Param_0,UADP_SDT_P2N, StreamID,VDEC_EX_STREAM_V2_ID, UADP_SDT_P2N,pRet,VDEC_EX_MS_U32);
    //E_VDEC_EX_V2_USER_CMD_SET_FRC_MODE
    UADP_SDT_NAME3(VDEC_EX_SET_FRC_MODE,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_FRC_MODE);
    //E_VDEC_EX_V2_USER_CMD_SET_DYNSCALING_PARAMS
    UADP_SDT_NAME4(VDEC_EX_SET_DYNSCALING_PARAMS,VDEC_EX_V2_IO_Param_2,UADP_SDT_P2N, StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N, param[0],VDEC_EX_MS_PHY ,UADP_SDT_P2N ,param[1],VDEC_EX_MS_U32);

    //E_VDEC_EX_V2_USER_CMD_SET_DBG_LEVEL
    UADP_SDT_NAME3(VDEC_EX_SET_DBG_LEVEL,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N, StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N, pRet,VDEC_EX_MS_U32,UADP_SDT_P2N, param[0],VDEC_EX_DBG_LEVEL);
    //E_VDEC_EX_V2_USER_CMD_SET_TRICK_MODE
    UADP_SDT_NAME3(VDEC_EX_SET_TRICK_MODE,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N, StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N, param[0],VDEC_EX_TRICK_DEC);
    //E_VDEC_EX_V2_USER_CMD_PUSH_DECQ
    UADP_SDT_NAME3(VDEC_EX_PUSH_DECQ,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_DEC_CMD);

    //E_VDEC_EX_V2_USER_CMD_FLUSH
    UADP_SDT_NAME3(VDEC_EX_FLUSH,VDEC_EX_V2_IO_Param_1, UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID, UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32, UADP_SDT_P2N, param[0],VDEC_EX_FREEZE_PIC_SELECT);
    //E_VDEC_EX_V2_USER_CMD_ENABLE_LAST_FRAME_SHOW:
    //E_VDEC_EX_V2_USER_CMD_SET_FREEZE_DISP:
    //E_VDEC_EX_V2_USER_CMD_SET_BLUE_SCREEN:
    //E_VDEC_EX_V2_USER_CMD_DISABLE_DEBLOCKING:
    //E_VDEC_EX_V2_USER_CMD_DISABLE_QUARTER_PIXEL:
    //E_VDEC_EX_V2_USER_CMD_SET_AUTO_RM_LST_ZERO_BYTE:
    //E_VDEC_EX_V2_USER_CMD_SET_BLOCK_DISPLAY:
    //E_VDEC_EX_V2_USER_CMD_ENABLE_ES_BUFF_MALLOC:
    UADP_SDT_NAME3(VDEC_EX_IO_BOOL,VDEC_EX_V2_IO_Param_1, UADP_SDT_P2N, StreamID,VDEC_EX_STREAM_V2_ID, UADP_SDT_P2N, pRet,VDEC_EX_MS_U32, UADP_SDT_P2N, param[0],VDEC_EX_BOOL);
    //E_VDEC_EX_V2_USER_CMD_SET_SPEED
    UADP_SDT_NAME4(VDEC_EX_SET_SPEED,VDEC_EX_V2_IO_Param_2,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID, UADP_SDT_P2N, pRet,VDEC_EX_MS_U32, UADP_SDT_P2N,param[0],VDEC_EX_SPEED_TYPE,UADP_SDT_P2N ,param[1],VDEC_EX_SPEED);
    //E_VDEC_EX_V2_USER_CMD_RESET_PTS:
    //E_VDEC_EX_V2_USER_CMD_AVSYNC_FREERUN_THRESHOLD:
    //E_VDEC_EX_V2_USER_CMD_SEEK_TO_PTS:
    //E_VDEC_EX_V2_USER_CMD_SKIP_TO_PTS:
    //E_VDEC_EX_V2_USER_CMD_CC_INIT;
    UADP_SDT_NAME3(VDEC_EX_IO_U32,VDEC_EX_V2_IO_Param_1, UADP_SDT_P2N, StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_MS_U32);
    //E_VDEC_EX_V2_USER_CMD_AVSYNC_ON
    UADP_SDT_NAME5(VDEC_EX_AVSYNC_ON,VDEC_EX_V2_IO_Param_3,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N, pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_BOOL,UADP_SDT_P2N, param[1],VDEC_EX_MS_U32,UADP_SDT_P2N ,param[2],VDEC_EX_MS_U16);
    //E_VDEC_EX_V2_USER_CMD_UNSET_EVENT_MULTICALLBACK
    UADP_SDT_NAME6(VDEC_EX_UNSET_EVENT_MULTICALLBACK,VDEC_EX_V2_IO_Param_4,UADP_SDT_P2N, StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N,param[0],VDEC_EX_TYPE,UADP_SDT_P2N,param[1],VDEC_EX_MS_U32,UADP_SDT_P2N,param[2],VDEC_EX_MS_U32,UADP_SDT_P2N,param[3],VDEC_EX_MS_U32);
    //E_VDEC_EX_V2_USER_CMD_SET_BALANCE_BW
    UADP_SDT_NAME6(VDEC_EX_SET_BALANCE_BW,VDEC_EX_V2_IO_Param_4,UADP_SDT_P2N, StreamID,VDEC_EX_STREAM_V2_ID, UADP_SDT_P2N, pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_MS_U8, UADP_SDT_P2N, param[1],VDEC_EX_MS_U8,UADP_SDT_P2N ,param[2],VDEC_EX_MS_U8,UADP_SDT_P2N ,param[3],VDEC_EX_MS_U8);
    //E_VDEC_EX_V2_USER_CMD_GEN_PATTERN
    UADP_SDT_NAME5(VDEC_EX_GEN_PATTERN,VDEC_EX_V2_IO_Param_3,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID, UADP_SDT_P2N,pRet,VDEC_EX_MS_U32, UADP_SDT_P2N ,param[0],VDEC_EX_PATTERN_TYPE, UADP_SDT_P2N, param[1],VDEC_EX_MS_PHY, UADP_SDT_P2N, param[2],VDEC_EX_MS_U32);
    //E_VDEC_EX_V2_USER_CMD_MHEG_DECODE_IFRAME:
    UADP_SDT_NAME5(VDEC_EX_MHEG_DECODE_IFRAME,VDEC_EX_V2_IO_Param_3, UADP_SDT_P2N, StreamID,VDEC_EX_STREAM_V2_ID, UADP_SDT_P2N, pRet,VDEC_EX_MS_U32, UADP_SDT_P2N, param[0],VDEC_EX_MS_PHY, UADP_SDT_P2N ,param[1],VDEC_EX_MS_PHY, UADP_SDT_P2N, param[2],VDEC_EX_MS_PHY);
    //E_VDEC_EX_V2_USER_CMD_CC_START_PARSING:
    UADP_SDT_NAME3(VDEC_EX_CC_START_PARSING,VDEC_EX_V2_IO_Param_1, UADP_SDT_P2N, StreamID,VDEC_EX_STREAM_V2_ID, UADP_SDT_P2N, pRet,VDEC_EX_MS_U32, UADP_SDT_P2N, param[0],VDEC_EX_CC_CONFIG);

    //E_VDEC_EX_V2_USER_CMD_DISPLAY_FRAME:
    UADP_SDT_NAME3(VDEC_EX_DISP_RELEASE_FRAME,VDEC_EX_V2_IO_Param_1, UADP_SDT_P2N, StreamID,VDEC_EX_STREAM_V2_ID, UADP_SDT_P2N, pRet,VDEC_EX_MS_U32, UADP_SDT_P2N, param[0],VDEC_EX_DISP_FRAME);
    //E_VDEC_EX_V2_USER_CMD_CAPTURE_FRAME
    UADP_SDT_NAME4(VDEC_EX_CAPTURE_FRAME,VDEC_EX_V2_IO_Param_2, UADP_SDT_P2N, StreamID,VDEC_EX_STREAM_V2_ID, UADP_SDT_P2N, pRet,VDEC_EX_MS_U32, UADP_SDT_P2N, param[0],VDEC_EX_MS_U32, UADP_SDT_P2N, param[1],VDEC_EX_BOOL);
    //E_VDEC_EX_V2_USER_CMD_CC_SET_CFG:
    UADP_SDT_NAME5(VDEC_EX_CC_SET_CFG,VDEC_EX_V2_IO_Param_3, UADP_SDT_P2N, StreamID,VDEC_EX_STREAM_V2_ID, UADP_SDT_P2N,pRet,VDEC_EX_MS_U32, UADP_SDT_P2N, param[0],VDEC_EX_CC_FORMAT, UADP_SDT_P2N, param[1],VDEC_EX_CC_TYPE, UADP_SDT_P2N, param[2],VDEC_EX_CC_INPUT_PARAM);
    //E_VDEC_EX_V2_USER_CMD_CC_SET_BUFF_START_ADDR
    //E_VDEC_EX_V2_USER_CMD_CC_UPDATE_WRITE_ADDR:
    //E_VDEC_EX_V2_USER_CMD_CC_UPDATE_READ_ADDR:
    UADP_SDT_NAME4(VDEC_EX_CC_UPDATE_ADDR,VDEC_EX_V2_IO_Param_2,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID, UADP_SDT_P2N, pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_CC_FORMAT, UADP_SDT_P2N,param[1],VDEC_EX_CC_INPUT_PARAM);
    //E_VDEC_EX_V2_USER_CMD_CC_DISABLE_PARSING:
    //E_VDEC_EX_V2_USER_CMD_CC_GET_IS_RST_DONE
    UADP_SDT_NAME3(VDEC_EX_CC_IO_CC_FORMAT,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_CC_FORMAT);
    //E_VDEC_EX_V2_USER_CMD_GETLIBVER:
    UADP_SDT_NAME3(VDEC_EX_GET_LIBVER,VDEC_EX_V2_IO_Param_1, UADP_SDT_P2N, StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32, UADP_SDT_P2N, param[0],VDEC_EX_MSIF_VERSION);
    //E_VDEC_EX_V2_USER_CMD_GETINFO:
    UADP_SDT_NAME3(VDEC_EX_GET_INFO,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32, UADP_SDT_P2N, param[0],VDEC_EX_MS_U32);

    //E_VDEC_EX_V2_USER_CMD_CHECKCAPS
    UADP_SDT_NAME4(VDEC_EX_CHECK_CAPS,VDEC_EX_V2_IO_Param_2,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID, UADP_SDT_P2N,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_CODEC_TYPE, UADP_SDT_P2N, param[1],VDEC_EX_BOOL);
    //E_VDEC_EX_V2_USER_CMD_GET_ACTIVE_CODEC_TYPE
    UADP_SDT_NAME3(VDEC_EX_GET_ACTIVE_CODEC_TYPE,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_CODEC_TYPE);
    //E_VDEC_EX_V2_USER_CMD_GET_DISP_INFO:
    UADP_SDT_NAME3(VDEC_EX_GET_DISP_INFO,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_DISP_INFO);
    //E_VDEC_EX_V2_USER_CMD_GET_EXT_DISP_INFO
    UADP_SDT_NAME3(VDEC_EX_GET_EXT_DISP_INFO,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_EXT_DISP_INFO);
    //E_VDEC_EX_V2_USER_CMD_GET_DEC_FRAME_INFO
    UADP_SDT_NAME3(VDEC_EX_GET_DEC_FRAME_INFO,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N, StreamID,VDEC_EX_STREAM_V2_ID, UADP_SDT_P2N,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_FRAME_INFO);
    //E_VDEC_EX_V2_USER_CMD_GET_DEC_TIMECODE
    UADP_SDT_NAME3(VDEC_EX_GET_DEC_TIMECODE,VDEC_EX_V2_IO_Param_1, UADP_SDT_P2N, StreamID,VDEC_EX_STREAM_V2_ID, UADP_SDT_P2N, pRet,VDEC_EX_MS_U32,UADP_SDT_P2N, param[0],VDEC_EX_TIME_CODE);

    //E_VDEC_EX_V2_USER_CMD_GET_COLOUR_PRIMARIES
    UADP_SDT_NAME3(VDEC_EX_IO_U8,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID, UADP_SDT_P2N, pRet,VDEC_EX_MS_U32, UADP_SDT_P2N, param[0],VDEC_EX_MS_U8);
    //E_VDEC_EX_V2_USER_CMD_GET_FW_VERSION
    UADP_SDT_NAME4(VDEC_EX_GET_FW_VERSION,VDEC_EX_V2_IO_Param_2,UADP_SDT_P2N, StreamID,VDEC_EX_STREAM_V2_ID, UADP_SDT_P2N, pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_FW_TYPE,UADP_SDT_P2N ,param[1],VDEC_EX_MS_U32);
    //E_VDEC_EX_V2_USER_CMD_GET_VIDEO_PTS_STC_DELTA
    UADP_SDT_NAME3(VDEC_EX_SET_GET_U64,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_MS_U64);
    //E_VDEC_EX_V2_USER_CMD_GET_ERR_CODE
    UADP_SDT_NAME3(VDEC_EX_GET_ERR_CODE,VDEC_EX_V2_IO_Param_1, UADP_SDT_P2N,StreamID,VDEC_EX_STREAM_V2_ID, UADP_SDT_P2N, pRet,VDEC_EX_MS_U32, UADP_SDT_P2N ,param[0],VDEC_EX_ERR_CODE);
    //E_VDEC_EX_V2_USER_CMD_GET_CC_INFO
    UADP_SDT_NAME4(VDEC_EX_GET_CC_INFO,VDEC_EX_V2_IO_Param_2,UADP_SDT_P2N, StreamID,VDEC_EX_STREAM_V2_ID, UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32, UADP_SDT_P2N, param[0],VDEC_EX_CC_INFO, UADP_SDT_P2N, param[1],VDEC_EX_MS_U32);

    //E_VDEC_EX_V2_USER_CMD_GET_PATTERN_LEAST_LENGTH
    UADP_SDT_NAME4(VDEC_EX_GET_PATTERN_LEAST_LENGTH,VDEC_EX_V2_IO_Param_2, UADP_SDT_P2N, StreamID,VDEC_EX_STREAM_V2_ID, UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32, UADP_SDT_P2N ,param[0],VDEC_EX_PATTERN_TYPE, UADP_SDT_P2N, param[1],VDEC_EX_MS_U32);
    //E_VDEC_EX_V2_USER_CMD_GET_ES_BUFF
    UADP_SDT_NAME5(VDEC_EX_GET_ES_BUFF,VDEC_EX_V2_IO_Param_3, UADP_SDT_P2N, StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_MS_U32, UADP_SDT_P2N, param[1],VDEC_EX_MS_U32,UADP_SDT_P2N ,param[2],VDEC_EX_MS_PHY);
    //E_VDEC_EX_V2_USER_CMD_CC_GET_INFO
    UADP_SDT_NAME5(VDEC_EX_CC_GET_INFO,VDEC_EX_V2_IO_Param_3, UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID, UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_CC_FORMAT,UADP_SDT_P2N ,param[1],VDEC_EX_CC_INFO_CMD,UADP_SDT_P2N, param[2],VDEC_EX_MS_U32);
    //E_VDEC_EX_V2_USER_CMD_CC_GET_WRITE_ADDR
    UADP_SDT_NAME4(VDEC_EX_GET_CC_GET_RW_ADDR,VDEC_EX_V2_IO_Param_2,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_CC_FORMAT,UADP_SDT_P2N ,param[1],VDEC_EX_MS_PHY);
    //E_VDEC_EX_V2_USER_CMD_FRC_OUTPUT
    UADP_SDT_NAME0(VDEC_EX_FRC_OUTPUT_PARAM,VDEC_EX_FRC_OutputParam);
    UADP_SDT_NAME1(VDEC_EX_PTR_FRC_OUTPUT_PARAM,VDEC_EX_PtrFRC_OutputParam,UADP_SDT_P2N ,pVDEC_EX_FRC_OutputParam,VDEC_EX_FRC_OUTPUT_PARAM);
    UADP_SDT_NAME3(VDEC_EX_FRC_OUTPUT,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_PTR_FRC_OUTPUT_PARAM);
    
    //E_VDEC_EX_V2_USER_CMD_UT_SET_DBG_MODE
    UADP_SDT_NAME3(VDEC_EX_UT_SET_DBG_MODE,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N, pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_DBG_MODE);
    //E_VDEC_EX_V2_USER_CMD_FIELD_POLARITY_DISPLAY_ONE_FIELD
    UADP_SDT_NAME3(VDEC_EX_FIELD_POLARITY_DISPLAY_ONE_FIELD,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_FIELD_POLARITY);
    //E_VDEC_EX_V2_USER_CMD_SET_EXTERNAL_DS_BUFFER
    UADP_SDT_NAME3(VDEC_EX_SET_EXTERNAL_DS_BUFFER,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_EXTERNAL_DS_BUF);

    //E_VDEC_EX_V2_USER_CMD_ENABLE_DECODE_ENGINE_TIMEOUT
    UADP_SDT_NAME1(VDEC_EX_PTR_TIMEOUT_PARAM,VDEC_EX_PtrTIMEOUT_PARAM,UADP_SDT_P2N ,pVDEC_EX_Decode_Timeout_Param,VDEC_EX_TIMEOUT_PARAM);
    UADP_SDT_NAME3(VDEC_EX_ENABLE_DECODE_ENGINE_TIMEOUT,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_PTR_TIMEOUT_PARAM);
    //E_VDEC_EX_V2_USER_CMD_SET_ERROR_TOLERANCE
//    UADP_SDT_NAME3(VDEC_EX_SET_ERROR_TOLERANCE,VDEC_EX_V2_IO_Param,UADP_SDT_P2N, StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N, pRet,VDEC_EX_MS_U32,UADP_SDT_P2N, param[0],VDEC_EX_ERR_TOLERANCE);
    UADP_SDT_NAME0(VDEC_EX_ERR_TOLERANCE,VDEC_EX_Err_Tolerance);
    UADP_SDT_NAME1(VDEC_EX_PTR_ERR_TOLERANCE,VDEC_EX_PtrErr_Tolerance,UADP_SDT_P2N ,pVDEC_EX_Err_Tolerance,VDEC_EX_ERR_TOLERANCE);
    UADP_SDT_NAME3(VDEC_EX_SET_ERROR_TOLERANCE,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N, StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N, pRet,VDEC_EX_MS_U32,UADP_SDT_P2N, param[0],VDEC_EX_PTR_ERR_TOLERANCE);
    
    //E_VDEC_EX_V2_USER_CMD_GET_MAIN_STREAM_ID
    UADP_SDT_NAME3(VDEC_EX_GET_STREAM_ID,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N, StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_STREAM_ID);
    //E_VDEC_EX_V2_USER_CMD_GET_FPA_SEI
    UADP_SDT_NAME3(VDEC_EX_GET_FPA_SEI,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32, UADP_SDT_P2N, param[0],VDEC_EX_FRAME_PACKING_SIE);
    //E_VDEC_EX_V2_USER_CMD_GET_FPA_SEI_EX
    UADP_SDT_NAME3(VDEC_EX_GET_FPA_SEI_EX,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID, UADP_SDT_P2N, pRet,VDEC_EX_MS_U32, UADP_SDT_P2N, param[0],VDEC_EX_VER_CTRL);
    //E_VDEC_EX_V2_USER_CMD_GET_CRC_VALUE
    UADP_SDT_NAME3(VDEC_EX_GET_CRC_VALUE,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N, StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N, pRet,VDEC_EX_MS_U32, UADP_SDT_P2N ,param[0],VDEC_EX_CRC_VALUE);
    //E_VDEC_EX_V2_USER_CMD_GET_FRAME_INFO_EX:
    UADP_SDT_NAME3(VDEC_EX_GET_FRAME_INFO_EX,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID, UADP_SDT_P2N,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_FRAME_INFO_EX);
    //E_VDEC_EX_V2_USER_CMD_GET_NEXT_DISP_FRAME_INFO_EXT:
    UADP_SDT_NAME3(VDEC_EX_GET_FRAME_INFO_EXT,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N, pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_FRAME_INFO_EXT);
    #ifdef VDEC_CAP_FRAME_INFO_EXT_V6
        UADP_SDT_NAME3(VDEC_EX_GET_FRAME_INFO_V6,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N, pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_FRAME_INFO_V6);
    #endif
    #ifdef VDEC_CAP_FRAME_INFO_EXT_V5
        UADP_SDT_NAME3(VDEC_EX_GET_FRAME_INFO_V5,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N, pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_FRAME_INFO_V5);
    #endif
    #ifdef VDEC_CAP_FRAME_INFO_EXT_V4
        UADP_SDT_NAME3(VDEC_EX_GET_FRAME_INFO_V4,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N, pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_FRAME_INFO_V4);
    #endif
    #ifdef VDEC_CAP_HEVC_HDR_V3
        UADP_SDT_NAME3(VDEC_EX_GET_FRAME_INFO_V3,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N, pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_FRAME_INFO_V3);
    #endif
    #ifdef VDEC_CAP_HEVC_HDR_V2
        UADP_SDT_NAME3(VDEC_EX_GET_FRAME_INFO_V2,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N, pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_FRAME_INFO_V2);
    #endif
        UADP_SDT_NAME3(VDEC_EX_GET_FRAME_INFO_V0,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N, pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_FRAME_INFO_V0);
    //E_VDEC_EX_V2_USER_CMD_PREGETSTATUS
    UADP_SDT_NAME3(VDEC_EX_PREGETSTATUS,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N, StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_STATUS);
    //E_VDEC_EX_V2_USER_CMD_SYSTEM_PRESET_VPU_CLOCK
    UADP_SDT_NAME3(VDEC_EX_SYSTEM_PRESET_CLOCK,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID, UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_CLOCK_SPEED);
    //E_VDEC_EX_V2_USER_CMD_SETPOWERSTATE
    UADP_SDT_NAME3(VDEC_EX_SET_POWERSTATE,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_POWER_MODE);
    //E_VDEC_EX_V2_USER_CMD_PRESET_DECODE_MODE

    UADP_SDT_NAME1(VDEC_EX_PTR_DEC_MOD_CFG,VDEC_EX_PtrDecModCfg,UADP_SDT_P2N ,pVDEC_EX_DecModCfg,VDEC_EX_DEC_MOD_CFG);
    UADP_SDT_NAME3(VDEC_EX_PRESET_DECODE_MODE,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_PTR_DEC_MOD_CFG);
    //E_VDEC_EX_V2_USER_CMD_HVD_IAPGN_BUF_SHARE_BW_MODE

    UADP_SDT_NAME1(VDEC_EX_PTR_IAP_GnBufShareBWMode,VDEC_EX_PtrIapGnBufShareBWMode,UADP_SDT_P2N ,pVDEC_EX_IapGnBufShareBWMode,VDEC_EX_IAP_GnBufShareBWMode);
    UADP_SDT_NAME3(VDEC_EX_HVD_IAPGN_BUF_SHARE_BW_MODE,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_PTR_IAP_GnBufShareBWMode);
    //E_VDEC_EX_V2_USER_CMD_GET_EVENT_FLAG
    UADP_SDT_NAME4(VDEC_EX_GET_EVENT_FLAG,VDEC_EX_V2_IO_Param_2,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N, param[0],VDEC_EX_MS_U32,UADP_SDT_P2N ,param[1],VDEC_EX_MS_U32);

    //E_VDEC_EX_V2_USER_CMD_SET_FRAMEBUFF2
    UADP_SDT_NAME0(VDEC_EX_FRAMEBUFF,VDEC_FRAMEBuff);
    UADP_SDT_NAME3(VDEC_EX_SET_FRAMEBUFF2,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_FRAMEBUFF);

    //E_VDEC_EX_V2_USER_CMD_SET_TRICKPLAY_2X_MODE:
    UADP_SDT_NAME0(VDEC_EX_TRICKPLAY_2X_MODE,VDEC_EX_TrickPlay2xMode);
    UADP_SDT_NAME3(VDEC_EX_SET_TRICKPLAY_2X_MODE,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_TRICKPLAY_2X_MODE);    

    //E_VDEC_EX_V2_USER_CMD_GET_DCV_SEI
    UADP_SDT_NAME0(VDEC_EX_DCV_SEI,VDEC_EX_DisplayColourVolume_SEI);
    UADP_SDT_NAME3(VDEC_EX_GET_DCV_SEI,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_DCV_SEI);

    //E_VDEC_EX_V2_USER_CMD_GET_VUI_DISP_INFO
    UADP_SDT_NAME0(VDEC_EX_VUI_DISP_INFO,VDEC_EX_AVC_VUI_DISP_INFO);
    UADP_SDT_NAME3(VDEC_EX_GET_VUI_DISP_INFO,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_VUI_DISP_INFO);

    //E_VDEC_EX_V2_USER_CMD_AUTO_ARRANGE_FRAMEBUFFER_USAGE
    UADP_SDT_NAME0(VDEC_EX_FRAMEBUFFER_CTRL,VDEC_Framebuffer_Ctrl);
    UADP_SDT_NAME1(VDEC_EX_PTR_FRAMEBUFFER_CTRL,VDEC_PtrFramebuffer_Ctrl,UADP_SDT_P2N ,pVDEC_Framebuffer_Ctrl,VDEC_EX_FRAMEBUFFER_CTRL);
    UADP_SDT_NAME3(VDEC_EX_AUTO_ARRANGE_FRAMEBUFFER_USAGE,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_PTR_FRAMEBUFFER_CTRL);

    //E_VDEC_EX_V2_USER_CMD_MFCODEC_MODE
    UADP_SDT_NAME0(VDEC_EX_MFCODEC_MODE,VDEC_EX_MFCodec_mode);
    UADP_SDT_NAME3(VDEC_EX_SET_MFCODEC_MODE,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_MFCODEC_MODE);    

    //E_VDEC_EX_V2_USER_CMD_VDEC_FEATURE
    UADP_SDT_NAME0(VDEC_EX_VDEC_FEATURE,VDEC_EX_Feature);
    UADP_SDT_NAME3(VDEC_EX_SET_VDEC_FEATURE,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_VDEC_FEATURE);    

    //E_VDEC_EX_V2_USER_CMD_SET_DISPLAY_MODE
    UADP_SDT_NAME0(VDEC_EX_DISPLAYMODE,VDEC_EX_DISPLAY_MODE);
    UADP_SDT_NAME3(VDEC_EX_SET_DISPLAYMODE,VDEC_EX_V2_IO_Param_1,UADP_SDT_P2N ,StreamID,VDEC_EX_STREAM_V2_ID,UADP_SDT_P2N ,pRet,VDEC_EX_MS_U32,UADP_SDT_P2N ,param[0],VDEC_EX_DISPLAYMODE);    

    //E_VDEC_EX_V2_USER_CMD_GET_BUFFER_INFO
    //UADP_SDT_NAME1(VDEC_EX_BUFFER_INFO,VDEC_EX_BufferInfo,UADP_SDT_AT ,szSize,MS_NULL);
    UADP_SDT_NAME1(VDEC_EX_BUFFER_INFO,VDEC_EX_BufferInfo,UADP_SDT_AT ,szSize,VDEC_EX_MS_SIZE);
    UADP_SDT_NAME3(VDEC_EX_GET_BUFFER_INFO,VDEC_EX_V2_IO_Param_1, UADP_SDT_P2N, StreamID,VDEC_EX_STREAM_V2_ID, UADP_SDT_P2N, pRet,VDEC_EX_MS_U32, UADP_SDT_P2N, param[0],VDEC_EX_BUFFER_INFO);

    //E_VDEC_EX_V2_USER_CMD_SET_DYNAMIC_DISP_PATH
    UADP_SDT_NAME0(VDEC_EX_DYNAMIC_DISP_PATH,VDEC_EX_DynmcDispPath);
    UADP_SDT_NAME1(VDEC_EX_PTR_DYNAMIC_DISP_PATH,VDEC_EX_PtrDynmcDispPath,UADP_SDT_P2N ,pVDEC_EX_DynmcDispPath,VDEC_EX_DYNAMIC_DISP_PATH);
    UADP_SDT_NAME3(VDEC_EX_SET_DYNAMIC_DISP_PATH,VDEC_EX_V2_IO_Param_1, UADP_SDT_P2N, StreamID,VDEC_EX_STREAM_V2_ID, UADP_SDT_P2N, pRet,VDEC_EX_MS_U32, UADP_SDT_P2N, param[0],VDEC_EX_PTR_DYNAMIC_DISP_PATH);

    *pIoctl= (FUtopiaIOctl)VDEC_EX_adp_Ioctl;

    return 0;
}


MS_U32 VDEC_EX_adp_Ioctl(void* pInstanceTmp, MS_U32 u32Cmd, void* const pArgs)
{
    MS_U32 u32Ret = UTOPIA_STATUS_SUCCESS;
    char buffer_arg[8];

    VDEC_EX_V2_IO_Param IO_param;
    //VDEC_EX_V2_StreamId StreamID;
    //VDEC_EX_V2_Result vRet;
    //VDEC_EX_V2_IO_Param* user_IO_Param = pArgs;
    VDEC_EX_V2_IO_Param* kernel_IO_Param = &IO_param;
    //kernel_IO_Param->StreamID = (&StreamID);
    //kernel_IO_Param->pRet = (&vRet);
    /*
    MS_PHYADDR u32Addr = 0;
    VDEC_EX_V2_TrickDec eTrickDec = E_VDEC_EX_V2_TRICK_DEC_ALL;
    VDEC_EX_V2_CodecType eCodecType = E_VDEC_EX_V2_CODEC_TYPE_NONE;
    VDEC_EX_V2_PatternType ePattern = E_VDEC_EX_V2_PATTERN_FLUSH;
    VDEC_EX_V2_CCFormat eCCFormat = E_VDEC_EX_V2_CC_NONE;
    VDEC_EX_V2_DispInfo stDispInfo;
    VDEC_EX_V2_CC_Info stCCInfo;
    MS_BOOL bEnable = 0 ;
    MS_U32 u32Param0 = 0,u32Param1 = 0,u32Param2 = 0;
    MS_U16 u16Param0 = 0;
    MS_U8 u8Param0 = 0;
    MS_U64 u64Param0 = 0;
    */
    if (u32Cmd >= E_VDEC_EX_V2_CMD_MAX) return -ENOTTY;
    if (!access_ok(VERIFY_WRITE, (void *)pArgs, sizeof(*pArgs))) return -EFAULT;

    switch(u32Cmd)
    {
        case E_VDEC_EX_V2_CMD_GET_FREE_STREAM_ID:
            u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_FREE_STREAM_ID, spt_VDEC_EX_GET_FREE_STREAM_ID,buffer_arg,sizeof(buffer_arg));
            break;
        case E_VDEC_EX_V2_CMD_INIT:
            u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_INIT, spt_VDEC_EX_INIT,buffer_arg,sizeof(buffer_arg));
            break;
        case E_VDEC_EX_V2_CMD_SET_CONTROL:
            CPY_FROM_USER((void*)kernel_IO_Param, (VDEC_EX_V2_IO_Param*)pArgs, sizeof(VDEC_EX_V2_IO_Param));
            switch(kernel_IO_Param->eUserCmd)
            {
                case E_VDEC_EX_V2_USER_CMD_CHECK_DISPINFO_READY:
                case E_VDEC_EX_V2_USER_CMD_PLAY:
                case E_VDEC_EX_V2_USER_CMD_PAUSE:
                case E_VDEC_EX_V2_USER_CMD_RESUME:
                case E_VDEC_EX_V2_USER_CMD_STEP_DISP:
                case E_VDEC_EX_V2_USER_CMD_STEP_DECODE:
                case E_VDEC_EX_V2_USER_CMD_FIRE_DEC:
                case E_VDEC_EX_V2_USER_CMD_MHEG_RST_IFRAME_DEC:
                case E_VDEC_EX_V2_USER_CMD_CC_STOP_PARSING:
                case E_VDEC_EX_V2_USER_CMD_RST:
                case E_VDEC_EX_V2_USER_CMD_EXIT:
                case E_VDEC_EX_V2_USER_CMD_DROP_ONE_PTS:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_IO, spt_VDEC_EX_IO,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_SET_FRC_MODE:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_SET_FRC_MODE, spt_VDEC_EX_SET_FRC_MODE,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_SET_DYNSCALING_PARAMS:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_SET_DYNSCALING_PARAMS, spt_VDEC_EX_SET_DYNSCALING_PARAMS,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_SET_DBG_LEVEL:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_SET_DBG_LEVEL, spt_VDEC_EX_SET_DBG_LEVEL,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_SET_TRICK_MODE:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_SET_TRICK_MODE, spt_VDEC_EX_SET_TRICK_MODE,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_PUSH_DECQ:
                case E_VDEC_EX_V2_USER_CMD_MVC_BBU2_PUSH_PACKET:
                case E_VDEC_EX_V2_USER_CMD_MVC_BBU2_FIRE_DECCMD:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_PUSH_DECQ, spt_VDEC_EX_PUSH_DECQ,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_FLUSH:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_FLUSH, spt_VDEC_EX_FLUSH,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_ENABLE_LAST_FRAME_SHOW:
                case E_VDEC_EX_V2_USER_CMD_SET_FREEZE_DISP:
                case E_VDEC_EX_V2_USER_CMD_SET_BLUE_SCREEN:
                case E_VDEC_EX_V2_USER_CMD_DISABLE_DEBLOCKING:
                case E_VDEC_EX_V2_USER_CMD_DISABLE_QUARTER_PIXEL:
                case E_VDEC_EX_V2_USER_CMD_SET_AUTO_RM_LST_ZERO_BYTE:
                case E_VDEC_EX_V2_USER_CMD_SET_BLOCK_DISPLAY:
                case E_VDEC_EX_V2_USER_CMD_ENABLE_ES_BUFF_MALLOC:
                case E_VDEC_EX_V2_USER_CMD_REPEAT_LAST_FIELD:
                case E_VDEC_EX_V2_USER_CMD_FAST_DISPLAY:
                case E_VDEC_EX_V2_USER_CMD_IGNORE_ERR_REF:
                case E_VDEC_EX_V2_USER_CMD_FORCE_FOLLOW_DTV_SPEC:
                case E_VDEC_EX_V2_USER_CMD_DISABLE_SEQ_CHG:
                case E_VDEC_EX_V2_USER_CMD_DTV_RESET_MVD_PARSER:
                case E_VDEC_EX_V2_USER_CMD_SET_DISP_OUTSIDE_CTRL_MODE:
                case E_VDEC_EX_V2_USER_CMD_RELEASE_FD_MASK:
                case E_VDEC_EX_V2_USER_CMD_FLUSH_PTS_BUF:
                case E_VDEC_EX_V2_USER_CMD_SUPPORT_AVC_TO_MVC:
                case E_VDEC_EX_V2_USER_CMD_3DLR_VIEW_EXCHANGE:
                case E_VDEC_EX_V2_USER_CMD_AVC_NEW_SLOW_MOTION:
                case E_VDEC_EX_V2_USER_CMD_SET_VSIZE_ALIGN:
                case E_VDEC_EX_V2_USER_CMD_SHOW_DECODE_ORDER:
                case E_VDEC_EX_V2_USER_CMD_AVC_DISP_IGNORE_CROP:
                case E_VDEC_EX_V2_USER_CMD_SUSPEND_DYNAMIC_SCALE:
                case E_VDEC_EX_V2_USER_CMD_FORCE_AUTO_MUTE:
                case E_VDEC_EX_V2_USER_CMD_SET_DISP_FINISH_MODE:
                case E_VDEC_EX_V2_USER_CMD_SET_AVSYNC_MODE:
                case E_VDEC_EX_V2_USER_CMD_PUSH_DISPQ_WITH_REF_NUM:
                case E_VDEC_EX_V2_USER_CMD_DS_RESV_N_BUFFER:
                case E_VDEC_EX_V2_USER_CMD_RM_ENABLE_PTS_TBL:
                case E_VDEC_EX_V2_USER_CMD_SET_CC608_INFO_ENHANCE_MODE:
                case E_VDEC_EX_V2_USER_CMD_IGNORE_PIC_OVERRUN:
                case E_VDEC_EX_V2_USER_CMD_CTL_SPEED_IN_DISP_ONLY:
                case E_VDEC_EX_V2_USER_CMD_AVC_SUPPORT_REF_NUM_OVER_MAX_DPB_SIZE:
                case E_VDEC_EX_V2_USER_CMD_RETURN_INVALID_AFD:
                case E_VDEC_EX_V2_USER_CMD_AVC_FORCE_BROKEN_BY_US:
                case E_VDEC_EX_V2_USER_CMD_DUAL_NON_BLOCK_MODE:
                case E_VDEC_EX_V2_USER_CMD_FRAMEBUFFER_AUTO_MODE:
                case E_VDEC_EX_V2_USER_CMD_SET_PTS_US_MODE:
                case E_VDEC_EX_V2_USER_CMD_AUTO_INSERT_DUMMY_DATA:
                case E_VDEC_EX_V2_USER_CMD_FRC_ONLY_SHOW_TOP_FIELD:
                case E_VDEC_EX_V2_USER_CMD_DISABLE_ES_FULL_STOP:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_IO_BOOL, spt_VDEC_EX_IO_BOOL,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_SET_SPEED:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_SET_SPEED, spt_VDEC_EX_SET_SPEED,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_RESET_PTS:
                case E_VDEC_EX_V2_USER_CMD_AVSYNC_FREERUN_THRESHOLD:
                case E_VDEC_EX_V2_USER_CMD_SEEK_TO_PTS:
                case E_VDEC_EX_V2_USER_CMD_SKIP_TO_PTS:
                case E_VDEC_EX_V2_USER_CMD_CC_INIT:
                case E_VDEC_EX_V2_USER_CMD_AVSYNC_REPEAT_TH:
                case E_VDEC_EX_V2_USER_CMD_DISP_ONE_FIELD:
                case E_VDEC_EX_V2_USER_CMD_FD_MASK_DELAY_COUNT:
                case E_VDEC_EX_V2_USER_CMD_FRC_DROP_TYPE:
                case E_VDEC_EX_V2_USER_CMD_AVC_MIN_FRM_GAP:
                case E_VDEC_EX_V2_USER_CMD_FORCE_INTERLACE_MODE:
                case E_VDEC_EX_V2_USER_CMD_SET_DTV_USER_DATA_MODE:
                case E_VDEC_EX_V2_USER_CMD_AUTO_EXHAUST_ES_MODE:
                case E_VDEC_EX_V2_USER_CMD_SHOW_FIRST_FRAME_DIRECT:
                case E_VDEC_EX_V2_USER_CMD_AVC_RESIZE_DOS_DISP_PEND_BUF:
                case E_VDEC_EX_V2_USER_CMD_SET_XC_LOW_DELAY_PARA:
                case E_VDEC_EX_V2_USER_CMD_SET_SECURE_MODE:
                case E_VDEC_EX_V2_USER_CMD_FRAMERATE_HANDLING:
                case E_VDEC_EX_V2_USER_CMD_RVU_SETTING_MODE:
                case E_VDEC_EX_V2_USER_CMD_IGNORE_PIC_STRUCT_DISPLAY:
                case E_VDEC_EX_V2_USER_CMD_INPUT_PTS_FREERUN_MODE:
                case E_VDEC_EX_V2_USER_CMD_ERR_CONCEAL_SLICE_1ST_MB:
                case E_VDEC_EX_V2_USER_CMD_SET_MIN_TSP_DATA_SIZE:
                case E_VDEC_EX_V2_USER_CMD_SET_DMX_FRAMERATE:
                case E_VDEC_EX_V2_USER_CMD_SET_DMX_FRAMERATEBASE:
                case E_VDEC_EX_V2_USER_CMD_ENABLE_CC_608_EXTERNAL_BUFFER:
                case E_VDEC_EX_V2_USER_CMD_ENABLE_CC_708_EXTERNAL_BUFFER:
                case E_VDEC_EX_V2_USER_CMD_SET_TIME_INC_PREDICT_PARA:
                case E_VDEC_EX_V2_USER_CMD_DIRECT_STC_MODE:
                case E_VDEC_EX_V2_USER_CMD_SET_AVSYNC_DISP_AUTO_DROP:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_IO_U32, spt_VDEC_EX_IO_U32,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_AVSYNC_ON:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_AVSYNC_ON, spt_VDEC_EX_AVSYNC_ON,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_SET_EVENT_MULTICALLBACK:
                case E_VDEC_EX_V2_USER_CMD_UNSET_EVENT_MULTICALLBACK:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_UNSET_EVENT_MULTICALLBACK, spt_VDEC_EX_UNSET_EVENT_MULTICALLBACK,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_SET_BALANCE_BW:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_SET_BALANCE_BW, spt_VDEC_EX_SET_BALANCE_BW,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GEN_PATTERN:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GEN_PATTERN, spt_VDEC_EX_GEN_PATTERN,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_MHEG_DECODE_IFRAME:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_MHEG_DECODE_IFRAME, spt_VDEC_EX_MHEG_DECODE_IFRAME,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_CC_START_PARSING:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_CC_START_PARSING, spt_VDEC_EX_CC_START_PARSING,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_DISPLAY_FRAME:
                case E_VDEC_EX_V2_USER_CMD_RELEASE_FRAME:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_DISP_RELEASE_FRAME, spt_VDEC_EX_DISP_RELEASE_FRAME,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_CAPTURE_FRAME:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_CAPTURE_FRAME, spt_VDEC_EX_CAPTURE_FRAME,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_CC_SET_CFG:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_CC_SET_CFG, spt_VDEC_EX_CC_SET_CFG,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_CC_SET_BUFF_START_ADDR:
                case E_VDEC_EX_V2_USER_CMD_CC_UPDATE_WRITE_ADDR:
                case E_VDEC_EX_V2_USER_CMD_CC_UPDATE_READ_ADDR:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_CC_UPDATE_ADDR, spt_VDEC_EX_CC_UPDATE_ADDR,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_CC_DISABLE_PARSING:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_CC_IO_CC_FORMAT, spt_VDEC_EX_CC_IO_CC_FORMAT,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_FRC_OUTPUT:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_FRC_OUTPUT, spt_VDEC_EX_FRC_OUTPUT,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_UT_SET_DBG_MODE:
                case E_VDEC_EX_V2_USER_CMD_UT_CLR_DBG_MODE:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_UT_SET_DBG_MODE, spt_VDEC_EX_UT_SET_DBG_MODE,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_SET_IDCT_MODE:
                case E_VDEC_EX_V2_USER_CMD_DROP_ERR_FRAME:
                case E_VDEC_EX_V2_USER_CMD_SET_SELF_SEQCHANGE:
                case E_VDEC_EX_V2_USER_CMD_SET_SMOOTH_REWIND:
                case E_VDEC_EX_V2_USER_CMD_PVR_TIMESHIFT_SEAMLESS_MODE:
                case E_VDEC_EX_V2_USER_CMD_SET_MBX_PARAM:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_IO_U8, spt_VDEC_EX_IO_U8,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_FIELD_POLARITY_DISPLAY_ONE_FIELD:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_FIELD_POLARITY_DISPLAY_ONE_FIELD, spt_VDEC_EX_FIELD_POLARITY_DISPLAY_ONE_FIELD,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_SET_EXTERNAL_DS_BUFFER:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_SET_EXTERNAL_DS_BUFFER, spt_VDEC_EX_SET_EXTERNAL_DS_BUFFER,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_ENABLE_DECODE_ENGINE_TIMEOUT:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_ENABLE_DECODE_ENGINE_TIMEOUT, spt_VDEC_EX_ENABLE_DECODE_ENGINE_TIMEOUT,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_SET_ERROR_TOLERANCE:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_SET_ERROR_TOLERANCE, spt_VDEC_EX_SET_ERROR_TOLERANCE,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_SET_FRAMEBUFF2:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_SET_FRAMEBUFF2, spt_VDEC_EX_SET_FRAMEBUFF2,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_SET_TRICKPLAY_2X_MODE:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_SET_TRICKPLAY_2X_MODE, spt_VDEC_EX_SET_TRICKPLAY_2X_MODE,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_SET_BUFFER_INFO:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_BUFFER_INFO, spt_VDEC_EX_GET_BUFFER_INFO,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_PVR_FLUSH_FRAME_BUFFER:
                case E_VDEC_EX_V2_USER_CMD_AVC_DISABLE_ANTI_VDEAD:
                case E_VDEC_EX_V2_USER_CMD_CC_GET_WRITE_PTR://unused
                case E_VDEC_EX_V2_USER_CMD_CC_GET_READ_PTR:
                case E_VDEC_EX_V2_USER_CMD_CC_UPDATE_READ_PTR:
                default:
                    break;
            }

            break;
        case E_VDEC_EX_V2_CMD_GET_CONTROL:
            CPY_FROM_USER((void*)kernel_IO_Param, pArgs, sizeof(VDEC_EX_V2_IO_Param));
            switch(kernel_IO_Param->eUserCmd)
            {
                case E_VDEC_EX_V2_USER_CMD_GETLIBVER:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_LIBVER, spt_VDEC_EX_GET_LIBVER,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GETINFO:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_INFO, spt_VDEC_EX_GET_INFO,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_CHECKCAPS:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_CHECK_CAPS, spt_VDEC_EX_CHECK_CAPS,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_ACTIVE_CODEC_TYPE:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_ACTIVE_CODEC_TYPE, spt_VDEC_EX_GET_ACTIVE_CODEC_TYPE,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_IS_STEP_DISP_DONE:
                case E_VDEC_EX_V2_USER_CMD_IS_STEP_DECODE_DONE:
                case E_VDEC_EX_V2_USER_CMD_IS_DISP_FINISH:
                case E_VDEC_EX_V2_USER_CMD_IS_AVSYNC_ON:
                case E_VDEC_EX_V2_USER_CMD_IS_WITH_VALID_STREAM:
                case E_VDEC_EX_V2_USER_CMD_IS_IFRAME_FOUND:
                case E_VDEC_EX_V2_USER_CMD_IS_SEQ_CHG:
                case E_VDEC_EX_V2_USER_CMD_IS_REACH_SYNC:
                case E_VDEC_EX_V2_USER_CMD_IS_START_SYNC:
                case E_VDEC_EX_V2_USER_CMD_IS_FREERUN:
                case E_VDEC_EX_V2_USER_CMD_IS_WITH_LOW_DELAY:
                case E_VDEC_EX_V2_USER_CMD_IS_ALL_BUFFER_EMPTY:
                case E_VDEC_EX_V2_USER_CMD_IS_FRAME_RDY:
                case E_VDEC_EX_V2_USER_CMD_IS_ALIVE:
                case E_VDEC_EX_V2_USER_CMD_MHEG_IS_IFRAME_DECODING:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_IO, spt_VDEC_EX_IO,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_DECQ_VACANCY:
                case E_VDEC_EX_V2_USER_CMD_GET_ES_WRITE_PTR:
                case E_VDEC_EX_V2_USER_CMD_GET_ES_READ_PTR:
                case E_VDEC_EX_V2_USER_CMD_GET_PTS:
                case E_VDEC_EX_V2_USER_CMD_GET_NEXT_PTS:
                case E_VDEC_EX_V2_USER_CMD_GET_ERR_CNT:
                case E_VDEC_EX_V2_USER_CMD_GET_BITRATE:
                case E_VDEC_EX_V2_USER_CMD_GET_FRAME_CNT:
                case E_VDEC_EX_V2_USER_CMD_GET_SKIP_CNT:
                case E_VDEC_EX_V2_USER_CMD_GET_DROP_CNT:
                case E_VDEC_EX_V2_USER_CMD_GET_DISP_CNT:
                case E_VDEC_EX_V2_USER_CMD_GET_ES_BUFF_VACANCY:
                case E_VDEC_EX_V2_USER_CMD_GET_CHROMA_TYPE:
                case E_VDEC_EX_V2_USER_CMD_GET_REAL_FRAMERATE:
                case E_VDEC_EX_V2_USER_CMD_GET_ES_QUANTITY:
                case E_VDEC_EX_V2_USER_CMD_GET_COLOR_MATRIX:
                case E_VDEC_EX_V2_USER_CMD_GET_DYNSCALE_ENABLED:
                case E_VDEC_EX_V2_USER_CMD_GET_ES2_QUANTITY:
                case E_VDEC_EX_V2_USER_CMD_GET_MVC_BBU2_DECQ_VACANCY:
                case E_VDEC_EX_V2_USER_CMD_GET_MVC_ES2_READ_PTR:
                case E_VDEC_EX_V2_USER_CMD_GET_MVC_ES2_WRITE_PTR:
                case E_VDEC_EX_V2_USER_CMD_GET_ORI_INTERLACE_MODE:
                case E_VDEC_EX_V2_USER_CMD_GET_MBS_ONLY_FLAG:
                case E_VDEC_EX_V2_USER_CMD_GET_BBU_Q_NUM:
                case E_VDEC_EX_V2_USER_CMD_GET_DISP_FRAME_NUM:
                case E_VDEC_EX_V2_USER_CMD_GET_ES_BUFFER_STATUS:
                case E_VDEC_EX_V2_USER_CMD_GET_CODEC_TYPE:
                case E_VDEC_EX_V2_USER_CMD_GET_SHAREMEMORY_BASE:
                case E_VDEC_EX_V2_USER_CMD_GET_XC_LOW_DELAY_INT_STATE:
                case E_VDEC_EX_V2_USER_CMD_GET_IS_LEAST_DISPQ_SIZE_FLAG:
                case E_VDEC_EX_V2_USER_CMD_GET_FIELD_PIC_FLAG:
                case E_VDEC_EX_V2_USER_CMD_GET_VSYNC_BRIDGE_ADDR:
                case E_VDEC_EX_V2_USER_CMD_GET_EVENT_INFO:
                case E_VDEC_EX_V2_USER_CMD_GET_FLUSH_PATTEN_ENTRY_NUM:
                case E_VDEC_EX_V2_USER_CMD_GET_DS_BUF_MIU_SEL:
                case E_VDEC_EX_V2_USER_CMD_GET_FW_STATUS_FLAG:
                case E_VDEC_EX_V2_USER_CMD_GET_HW_MAX_PIXEL:
                case E_VDEC_EX_V2_USER_CMD_GET_VSYNC_BRIDGE_EXT_ADDR:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_IO_U32, spt_VDEC_EX_IO_U32,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_EVENT_FLAG:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_EVENT_FLAG, spt_VDEC_EX_GET_EVENT_FLAG,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_DISP_INFO:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_DISP_INFO, spt_VDEC_EX_GET_DISP_INFO,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_EXT_DISP_INFO:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_EXT_DISP_INFO, spt_VDEC_EX_GET_EXT_DISP_INFO,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_DEC_FRAME_INFO:
                case E_VDEC_EX_V2_USER_CMD_GET_DISP_FRAME_INFO:
                case E_VDEC_EX_V2_USER_CMD_GET_MVC_SUB_FRAME_DISP_INFO:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_DEC_FRAME_INFO, spt_VDEC_EX_GET_DEC_FRAME_INFO,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_DEC_TIMECODE:
                case E_VDEC_EX_V2_USER_CMD_GET_DISP_TIMECODE:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_DEC_TIMECODE, spt_VDEC_EX_GET_DEC_TIMECODE,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_COLOUR_PRIMARIES:
                case E_VDEC_EX_V2_USER_CMD_GET_GOP_CNT:
                case E_VDEC_EX_V2_USER_CMD_GET_HW_KEY:
                case E_VDEC_EX_V2_USER_CMD_GET_ACTIVE_FORMAT:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_IO_U8, spt_VDEC_EX_IO_U8,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_FW_VERSION:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_FW_VERSION, spt_VDEC_EX_GET_FW_VERSION,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_VIDEO_PTS_STC_DELTA:
                case E_VDEC_EX_V2_USER_CMD_GET_U64PTS:
                case E_VDEC_EX_V2_USER_CMD_GET_PRE_PAS_U64PTS:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_SET_GET_U64, spt_VDEC_EX_SET_GET_U64,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_ERR_CODE:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_ERR_CODE, spt_VDEC_EX_GET_ERR_CODE,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_IS_32_PULLDOWN:
                case E_VDEC_EX_V2_USER_CMD_IS_CC_AVAILABLE:
                case E_VDEC_EX_V2_USER_CMD_CC_GET_IS_OVERFLOW:
                case E_VDEC_EX_V2_USER_CMD_GET_SUPPORT_2ND_MVOP_INTERFACE:
                case E_VDEC_EX_V2_USER_CMD_GET_SECURE_MODE:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_IO_BOOL, spt_VDEC_EX_IO_BOOL,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_CC_INFO:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_CC_INFO, spt_VDEC_EX_GET_CC_INFO,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_TRICK_MODE:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_SET_TRICK_MODE, spt_VDEC_EX_SET_TRICK_MODE,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_PATTERN_LEAST_LENGTH:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_PATTERN_LEAST_LENGTH, spt_VDEC_EX_GET_PATTERN_LEAST_LENGTH,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_ES_BUFF:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_ES_BUFF, spt_VDEC_EX_GET_ES_BUFF,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_NEXT_DISP_FRAME:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_DISP_RELEASE_FRAME, spt_VDEC_EX_DISP_RELEASE_FRAME,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_CC_GET_INFO:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_CC_GET_INFO, spt_VDEC_EX_CC_GET_INFO,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_CC_GET_IS_RST_DONE:
                case E_VDEC_EX_V2_USER_CMD_CC_GET_IS_BUFF_OVERFLOW:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_CC_IO_CC_FORMAT, spt_VDEC_EX_CC_IO_CC_FORMAT,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_CC_GET_WRITE_ADDR:
                case E_VDEC_EX_V2_USER_CMD_CC_GET_READ_ADDR:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_CC_GET_RW_ADDR, spt_VDEC_EX_GET_CC_GET_RW_ADDR,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_MAIN_STREAM_ID:
                case E_VDEC_EX_V2_USER_CMD_GET_SUB_STREAM_ID:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_STREAM_ID, spt_VDEC_EX_GET_STREAM_ID,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_FPA_SEI:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_FPA_SEI, spt_VDEC_EX_GET_FPA_SEI,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_FPA_SEI_EX:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_FPA_SEI_EX, spt_VDEC_EX_GET_FPA_SEI_EX,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_CRC_VALUE:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_CRC_VALUE, spt_VDEC_EX_GET_CRC_VALUE,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_FRAME_INFO_EX:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_FRAME_INFO_EX, spt_VDEC_EX_GET_FRAME_INFO_EX,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_NEXT_DISP_FRAME_INFO_EXT:
                    {
                        VDEC_EX_VerCtl version;

#ifdef CONFIG_COMPAT
                        if(IS_CMP_TASK())
                        {
                            VDEC_EX_V2_IO_Param_32 __user *user_IO_Param;
                            user_IO_Param = (pArgs);
                            CMP_CPY_FROM_USER((VDEC_EX_VerCtl*)&version, user_IO_Param->param[0], sizeof(VDEC_EX_VerCtl));
                        }
                        else
#endif
                        {
                            VDEC_EX_V2_IO_Param* user_IO_Param = pArgs;
                            CMP_CPY_FROM_USER((VDEC_EX_VerCtl*)&version, user_IO_Param->param[0], sizeof(VDEC_EX_VerCtl));
                        }
                        #ifdef VDEC_CAP_FRAME_INFO_EXT_V6
                        if(version.u32version == 6)
                        {
                            u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_FRAME_INFO_V6, spt_VDEC_EX_GET_FRAME_INFO_V6,buffer_arg,sizeof(buffer_arg));
                            break;
                        }
                        #endif
                        #ifdef VDEC_CAP_FRAME_INFO_EXT_V5
                        if(version.u32version == 5)
                        {
                            u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_FRAME_INFO_V5, spt_VDEC_EX_GET_FRAME_INFO_V5,buffer_arg,sizeof(buffer_arg));
                            break;
                        }
                        #endif
                        #ifdef VDEC_CAP_FRAME_INFO_EXT_V4
                        if(version.u32version == 4)
                        {
                            u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_FRAME_INFO_V4, spt_VDEC_EX_GET_FRAME_INFO_V4,buffer_arg,sizeof(buffer_arg));
                            break;
                        }
                        #endif
                        #ifdef VDEC_CAP_HEVC_HDR_V3
                        if(version.u32version == 3)
                        {
                            u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_FRAME_INFO_V3, spt_VDEC_EX_GET_FRAME_INFO_V3,buffer_arg,sizeof(buffer_arg));
                            break;
                        }
                        #endif
                        #ifdef VDEC_CAP_HEVC_HDR_V2
                        if(version.u32version == 2)
                        {
                            u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_FRAME_INFO_V2, spt_VDEC_EX_GET_FRAME_INFO_V2,buffer_arg,sizeof(buffer_arg));
                            break;
                        }
                        #endif
                        u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_FRAME_INFO_V0, spt_VDEC_EX_GET_FRAME_INFO_V0,buffer_arg,sizeof(buffer_arg));
                    }
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_FRAME_INFO_EXT, spt_VDEC_EX_GET_FRAME_INFO_EXT,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_DCV_SEI:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_DCV_SEI, spt_VDEC_EX_GET_DCV_SEI,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_VUI_DISP_INFO:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_VUI_DISP_INFO, spt_VDEC_EX_GET_VUI_DISP_INFO,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_BUFFER_INFO:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_BUFFER_INFO, spt_VDEC_EX_GET_BUFFER_INFO,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_SET_DYNAMIC_DISP_PATH:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_SET_DYNAMIC_DISP_PATH, spt_VDEC_EX_SET_DYNAMIC_DISP_PATH,buffer_arg,sizeof(buffer_arg));
                    break;
                default:
                    break;
            }
            break;
        case E_VDEC_EX_V2_CMD_PRE_SET_CONTROL:
            CPY_FROM_USER((void*)kernel_IO_Param, (VDEC_EX_V2_IO_Param*)pArgs, sizeof(VDEC_EX_V2_IO_Param));
            switch(kernel_IO_Param->eUserCmd)
            {
                case E_VDEC_EX_V2_USER_CMD_PREGETSTATUS:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_PREGETSTATUS, spt_VDEC_EX_PREGETSTATUS,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_PRESET_ENABLETURBOMODE:
                case E_VDEC_EX_V2_USER_CMD_PRESETSINGLEDECODE:
                case E_VDEC_EX_V2_USER_CMD_VPU_SECURITY_MODE:
                case E_VDEC_EX_V2_USER_CMD_HVD_COL_BBU_MODE:
                case E_VDEC_EX_V2_USER_CMD_HVD_ONE_PENDING_BUFFER_MODE:
                case E_VDEC_EX_V2_USER_CMD_MVD_HWBUFFER_REMAPPING_MODE:
                case E_VDEC_EX_V2_USER_CMD_HVD_TS_IN_BBU_MODE:
                case E_VDEC_EX_V2_USER_CMD_FORCE_8BIT_DEC_MODE:
                case E_VDEC_EX_V2_USER_CMD_BITSTREAMBUFFER_MONOPOLY:
                case E_VDEC_EX_V2_USER_CMD_FRAMEBUFFER_MONOPOLY:
                case E_VDEC_EX_V2_USER_CMD_SPECIFY_TASK_SPEC:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_IO_BOOL, spt_VDEC_EX_IO_BOOL,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_PRESET_DECODE_MODE:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_PRESET_DECODE_MODE, spt_VDEC_EX_PRESET_DECODE_MODE,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_SET_SHAREMEMORY_BASE:
                case E_VDEC_EX_V2_USER_CMD_PRESET_STC:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_IO_U32, spt_VDEC_EX_IO_U32,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_SYSTEM_PRESET_VPU_CLOCK:
                case E_VDEC_EX_V2_USER_CMD_SYSTEM_PRESET_HVD_CLOCK:
                case E_VDEC_EX_V2_USER_CMD_SYSTEM_PRESET_MVD_CLOCK:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_SYSTEM_PRESET_CLOCK, spt_VDEC_EX_SYSTEM_PRESET_CLOCK,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_SETPOWERSTATE:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_SET_POWERSTATE, spt_VDEC_EX_SET_POWERSTATE,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_HVD_IAPGN_BUF_SHARE_BW_MODE:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_HVD_IAPGN_BUF_SHARE_BW_MODE, spt_VDEC_EX_HVD_IAPGN_BUF_SHARE_BW_MODE,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_SET_TOTALRANGE_BITSTREAMBUFFER:
                case E_VDEC_EX_V2_USER_CMD_SET_TOTALRANGE_FRAMEBUFFER1:
                case E_VDEC_EX_V2_USER_CMD_SET_TOTALRANGE_FRAMEBUFFER2:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_SET_TOTALRANGE_BITSTREAMBUFFER, spt_VDEC_EX_SET_TOTALRANGE_BITSTREAMBUFFER,buffer_arg,sizeof(buffer_arg));
                case E_VDEC_EX_V2_USER_CMD_AUTO_ARRANGE_FRAMEBUFFER_USAGE:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_AUTO_ARRANGE_FRAMEBUFFER_USAGE, spt_VDEC_EX_AUTO_ARRANGE_FRAMEBUFFER_USAGE,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_MFCODEC_MODE:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_SET_MFCODEC_MODE, spt_VDEC_EX_SET_MFCODEC_MODE,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_VDEC_FEATURE:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_SET_VDEC_FEATURE, spt_VDEC_EX_SET_VDEC_FEATURE,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_SET_DISPLAY_MODE:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_SET_DISPLAYMODE, spt_VDEC_EX_SET_DISPLAYMODE,buffer_arg,sizeof(buffer_arg));
                    break;

                default:
                    break;
            }
            break;
        case E_VDEC_EX_V2_CMD_POST_SET_CONTROL:
            CPY_FROM_USER((void*)kernel_IO_Param, (VDEC_EX_V2_IO_Param*)pArgs, sizeof(VDEC_EX_V2_IO_Param));
            switch(kernel_IO_Param->eUserCmd)
            {
                case E_VDEC_EX_V2_USER_CMD_SYSTEM_POSTSET_CLEAR_PROCESS_RELATED:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_IO_U32, spt_VDEC_EX_IO_U32,buffer_arg,sizeof(buffer_arg));
                    break;
                default:
                    break;
            }
            break;
        default:
            break;
    }
    return u32Ret;
}

