////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2008-2009 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// (; MStar; Confidential; Information; ) by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
//****************************************************
//   FRC Map CodeGen Version 2.0
// FRC_mapping
// Einstein
// 7/29/2013  3:34:04 PM
// 39630.43853
//****************************************************

#ifndef _EINSTEIN_FRC_MAPPING_MODE_C_
#define _EINSTEIN_FRC_MAPPING_MODE_C_


// FRC_mapping
//****************************************************
// R2Y
//****************************************************
MS_U8 FRC_3D_R2Y_FRC_Mapping_mode[][REG_ADDR_SIZE+REG_MASK_SIZE+FRC_R2Y_NUMS_FRC_Mapping_mode]=
{      // Reg           Mask  Value
{    FRC_MAP_REG(REG_FRC_BK40_10_L),0x01,0x00/*OFF*/, 
                                       0x01/*ON*/, },
{    FRC_MAP_REG(REG_FRC_BK40_10_L),0x02,0x00/*OFF*/, 
                                       0x02/*ON*/, },
{    FRC_MAP_REG(REG_FRC_BK40_10_L),0x04,0x00/*OFF*/, 
                                       0x04/*ON*/, },
{    FRC_MAP_REG(REG_FRC_BK40_10_L),0x08,0x00/*OFF*/, 
                                       0x08/*ON*/, },
{    FRC_MAP_REG(REG_FRC_BK40_10_L),0x10,0x00/*OFF*/, 
                                       0x10/*ON*/, },
{    FRC_MAP_REG(REG_FRC_BK40_10_L),0x20,0x00/*OFF*/, 
                                       0x20/*ON*/, },
{    FRC_MAP_REG(REG_FRC_BK40_10_L),0x40,0x00/*OFF*/, 
                                       0x40/*ON*/, },
{     FRC_MAP_REG(REG_TABLE_END), 0x00, 0x00 }
};

//****************************************************
// MRW
//****************************************************
MS_U8 FRC_3D_MRW_FRC_Mapping_mode[][REG_ADDR_SIZE+REG_MASK_SIZE+FRC_MRW_NUMS_FRC_Mapping_mode]=
{      // Reg           Mask  Value
{    FRC_MAP_REG(REG_FRC_BK40_01_L),0x01,0x00/*OFF*/, 
                                       0x01/*ON*/, },
{    FRC_MAP_REG(REG_FRC_BK40_01_L),0x20,0x00/*OFF*/, 
                                       0x20/*ON*/, },
{    FRC_MAP_REG(REG_FRC_BK40_02_H),0x40,0x00/*OFF*/, 
                                       0x00/*ON*/, },
{    FRC_MAP_REG(REG_FRC_BK40_02_H),0x80,0x00/*OFF*/, 
                                       0x00/*ON*/, },
{     FRC_MAP_REG(REG_TABLE_END), 0x00, 0x00 }
};

//****************************************************
// HSD
//****************************************************
MS_U8 FRC_3D_HSD_FRC_Mapping_mode[][REG_ADDR_SIZE+REG_MASK_SIZE+FRC_HSD_NUMS_FRC_Mapping_mode]=
{      // Reg           Mask  Value
{    FRC_MAP_REG(REG_FRC_BK47_05_H),0x80,0x00/*OFF*/, },
{     FRC_MAP_REG(REG_TABLE_END), 0x00, 0x00 }
};

//****************************************************
// 444to422
//****************************************************
MS_U8 FRC_3D_444to422_FRC_Mapping_mode[][REG_ADDR_SIZE+REG_MASK_SIZE+FRC_444to422_NUMS_FRC_Mapping_mode]=
{      // Reg           Mask  Value
{    FRC_MAP_REG(REG_FRC_BK43_51_H),0x08,0x00/*OFF*/, 
                                       0x08/*ON*/, },
{    FRC_MAP_REG(REG_FRC_BK43_51_H),0x10,0x00/*OFF*/, 
                                       0x10/*ON*/, },
{     FRC_MAP_REG(REG_TABLE_END), 0x00, 0x00 }
};

//****************************************************
// VCE
//****************************************************
MS_U8 FRC_3D_VCE_FRC_Mapping_mode[][REG_ADDR_SIZE+REG_MASK_SIZE+FRC_VCE_NUMS_FRC_Mapping_mode]=
{      // Reg           Mask  Value
{    FRC_MAP_REG(REG_FRC_BK42_10_L),0x02,0x00/*OFF*/, 
                                       0x02/*ON*/, },
{    FRC_MAP_REG(REG_FRC_BK42_10_L),0x01,0x00/*OFF*/, 
                                       0x01/*ON*/, },
{    FRC_MAP_REG(REG_FRC_BK42_22_L),0xFF,0x00/*OFF*/, 
                                       0xC0/*ON*/, },
{    FRC_MAP_REG(REG_FRC_BK43_0A_L),0x07,0x05/*OFF*/, 
                                       0x01/*ON*/, },
{     FRC_MAP_REG(REG_TABLE_END), 0x00, 0x00 }
};

//****************************************************
// IPM_OPM
//****************************************************
MS_U8 FRC_3D_IPM_OPM_FRC_Mapping_mode[][REG_ADDR_SIZE+REG_MASK_SIZE+FRC_IPM_OPM_NUMS_FRC_Mapping_mode]=
{      // Reg           Mask  Value
{    FRC_MAP_REG(REG_FRC_BK43_14_H),0x01,0x00/*OFF*/, 
                                       0x01/*4k2k*/, 
                                       0x01/*24_60_4k2k*/, 
                                       0x01/*30_60_4k2k*/, 
                                       0x01/*fullHD*/, 
                                       0x01/*24_60_fullHD*/, 
                                       0x01/*30_60_fullHD*/, },
{    FRC_MAP_REG(REG_FRC_BK43_0D_L),0x04,0x00/*OFF*/, 
                                       0x04/*4k2k*/, 
                                       0x04/*24_60_4k2k*/, 
                                       0x04/*30_60_4k2k*/, 
                                       0x04/*fullHD*/, 
                                       0x04/*24_60_fullHD*/, 
                                       0x04/*30_60_fullHD*/, },
{    FRC_MAP_REG(REG_FRC_BK43_03_L),0xff,0x00/*OFF*/, 
                                       0x20/*4k2k*/, 
                                       0x24/*24_60_4k2k*/, 
                                       0x24/*30_60_4k2k*/, 
                                       0x20/*fullHD*/, 
                                       0x20/*24_60_fullHD*/, 
                                       0x20/*30_60_fullHD*/, },
{    FRC_MAP_REG(REG_FRC_BK43_03_H),0xff,0x00/*OFF*/, 
                                       0x30/*4k2k*/, 
                                       0x08/*24_60_4k2k*/, 
                                       0x08/*30_60_4k2k*/, 
                                       0x30/*fullHD*/, 
                                       0x30/*24_60_fullHD*/, 
                                       0x30/*30_60_fullHD*/, },
{    FRC_MAP_REG(REG_FRC_BK43_06_L),0xff,0x00/*OFF*/, 
                                       0x10/*4k2k*/, 
                                       0x0a/*24_60_4k2k*/, 
                                       0x0a/*30_60_4k2k*/, 
                                       0x10/*fullHD*/, 
                                       0x10/*24_60_fullHD*/, 
                                       0x10/*30_60_fullHD*/, },
{    FRC_MAP_REG(REG_FRC_BK43_06_H),0xff,0x00/*OFF*/, 
                                       0x10/*4k2k*/, 
                                       0x07/*24_60_4k2k*/, 
                                       0x07/*30_60_4k2k*/, 
                                       0x10/*fullHD*/, 
                                       0x10/*24_60_fullHD*/, 
                                       0x10/*30_60_fullHD*/, },
{    FRC_MAP_REG(REG_FRC_BK43_01_L),0x04,0x00/*OFF*/, 
                                       0x04/*4k2k*/, 
                                       0x04/*24_60_4k2k*/, 
                                       0x04/*30_60_4k2k*/, 
                                       0x04/*fullHD*/, 
                                       0x04/*24_60_fullHD*/, 
                                       0x04/*30_60_fullHD*/, },
{    FRC_MAP_REG(REG_FRC_BK43_68_H),0x1f,0x00/*OFF*/, 
                                       0x0f/*4k2k*/, 
                                       0x0f/*24_60_4k2k*/, 
                                       0x0f/*30_60_4k2k*/, 
                                       0x07/*fullHD*/, 
                                       0x07/*24_60_fullHD*/, 
                                       0x07/*30_60_fullHD*/, },
{    FRC_MAP_REG(REG_FRC_BK43_68_L),0xff,0x00/*OFF*/, 
                                       0x00/*4k2k*/, 
                                       0x00/*24_60_4k2k*/, 
                                       0x00/*30_60_4k2k*/, 
                                       0x80/*fullHD*/, 
                                       0x80/*24_60_fullHD*/, 
                                       0x80/*30_60_fullHD*/, },
{    FRC_MAP_REG(REG_FRC_BK43_69_H),0x0f,0x00/*OFF*/, 
                                       0x08/*4k2k*/, 
                                       0x08/*24_60_4k2k*/, 
                                       0x08/*30_60_4k2k*/, 
                                       0x04/*fullHD*/, 
                                       0x04/*24_60_fullHD*/, 
                                       0x04/*30_60_fullHD*/, },
{    FRC_MAP_REG(REG_FRC_BK43_69_L),0xff,0x00/*OFF*/, 
                                       0x70/*4k2k*/, 
                                       0x70/*24_60_4k2k*/, 
                                       0x70/*30_60_4k2k*/, 
                                       0x38/*fullHD*/, 
                                       0x38/*24_60_fullHD*/, 
                                       0x38/*30_60_fullHD*/, },
{    FRC_MAP_REG(REG_FRC_BK43_6A_H),0x1f,0x00/*OFF*/, 
                                       0x0f/*4k2k*/, 
                                       0x0f/*24_60_4k2k*/, 
                                       0x0f/*30_60_4k2k*/, 
                                       0x07/*fullHD*/, 
                                       0x07/*24_60_fullHD*/, 
                                       0x07/*30_60_fullHD*/, },
{    FRC_MAP_REG(REG_FRC_BK43_6A_L),0xff,0x00/*OFF*/, 
                                       0x00/*4k2k*/, 
                                       0x00/*24_60_4k2k*/, 
                                       0x00/*30_60_4k2k*/, 
                                       0x80/*fullHD*/, 
                                       0x80/*24_60_fullHD*/, 
                                       0x80/*30_60_fullHD*/, },
{    FRC_MAP_REG(REG_FRC_BK43_6B_H),0x0f,0x00/*OFF*/, 
                                       0x08/*4k2k*/, 
                                       0x08/*24_60_4k2k*/, 
                                       0x08/*30_60_4k2k*/, 
                                       0x04/*fullHD*/, 
                                       0x04/*24_60_fullHD*/, 
                                       0x04/*30_60_fullHD*/, },
{    FRC_MAP_REG(REG_FRC_BK43_6B_L),0xff,0x00/*OFF*/, 
                                       0x70/*4k2k*/, 
                                       0x70/*24_60_4k2k*/, 
                                       0x70/*30_60_4k2k*/, 
                                       0x38/*fullHD*/, 
                                       0x38/*24_60_fullHD*/, 
                                       0x38/*30_60_fullHD*/, },
{    FRC_MAP_REG(REG_FRC_BK43_0C_H),0x80,0x80/*OFF*/, 
                                       0x80/*4k2k*/, 
                                       0x80/*24_60_4k2k*/, 
                                       0x80/*30_60_4k2k*/, 
                                       0x80/*fullHD*/, 
                                       0x80/*24_60_fullHD*/, 
                                       0x80/*30_60_fullHD*/, },
{    FRC_MAP_REG(REG_FRC_BK43_0C_H),0x0f,0x00/*OFF*/, 
                                       0x00/*4k2k*/, 
                                       0x04/*24_60_4k2k*/, 
                                       0x04/*30_60_4k2k*/, 
                                       0x00/*fullHD*/, 
                                       0x02/*24_60_fullHD*/, 
                                       0x01/*30_60_fullHD*/, },
{    FRC_MAP_REG(REG_FRC_BK43_0C_L),0xff,0x00/*OFF*/, 
                                       0x01/*4k2k*/, 
                                       0xd8/*24_60_4k2k*/, 
                                       0x58/*30_60_4k2k*/, 
                                       0x01/*fullHD*/, 
                                       0x06/*24_60_fullHD*/, 
                                       0x03/*30_60_fullHD*/, },
{    FRC_MAP_REG(REG_FRC_BK43_14_H),0x02,0x00/*OFF*/, 
                                       0x02/*4k2k*/, 
                                       0x02/*24_60_4k2k*/, 
                                       0x02/*30_60_4k2k*/, 
                                       0x02/*fullHD*/, 
                                       0x02/*24_60_fullHD*/, 
                                       0x02/*30_60_fullHD*/, },
{    FRC_MAP_REG(REG_FRC_BK43_0D_L),0x02,0x00/*OFF*/, 
                                       0x02/*4k2k*/, 
                                       0x02/*24_60_4k2k*/, 
                                       0x02/*30_60_4k2k*/, 
                                       0x02/*fullHD*/, 
                                       0x02/*24_60_fullHD*/, 
                                       0x02/*30_60_fullHD*/, },
{    FRC_MAP_REG(REG_FRC_BK43_04_L),0xff,0x00/*OFF*/, 
                                       0x20/*4k2k*/, 
                                       0x20/*24_60_4k2k*/, 
                                       0x20/*30_60_4k2k*/, 
                                       0x20/*fullHD*/, 
                                       0x20/*24_60_fullHD*/, 
                                       0x20/*30_60_fullHD*/, },
{    FRC_MAP_REG(REG_FRC_BK43_04_H),0xff,0x00/*OFF*/, 
                                       0x10/*4k2k*/, 
                                       0x10/*24_60_4k2k*/, 
                                       0x10/*30_60_4k2k*/, 
                                       0x10/*fullHD*/, 
                                       0x10/*24_60_fullHD*/, 
                                       0x10/*30_60_fullHD*/, },
{    FRC_MAP_REG(REG_FRC_BK43_07_L),0xff,0x00/*OFF*/, 
                                       0x10/*4k2k*/, 
                                       0x0f/*24_60_4k2k*/, 
                                       0x0f/*30_60_4k2k*/, 
                                       0x10/*fullHD*/, 
                                       0x10/*24_60_fullHD*/, 
                                       0x10/*30_60_fullHD*/, },
{    FRC_MAP_REG(REG_FRC_BK43_07_H),0xff,0x00/*OFF*/, 
                                       0x10/*4k2k*/, 
                                       0x07/*24_60_4k2k*/, 
                                       0x07/*30_60_4k2k*/, 
                                       0x10/*fullHD*/, 
                                       0x10/*24_60_fullHD*/, 
                                       0x10/*30_60_fullHD*/, },
{    FRC_MAP_REG(REG_FRC_BK43_72_L),0xff,0x00/*OFF*/, 
                                       0x00/*4k2k*/, 
                                       0x00/*24_60_4k2k*/, 
                                       0x00/*30_60_4k2k*/, 
                                       0x00/*fullHD*/, 
                                       0x00/*24_60_fullHD*/, 
                                       0x00/*30_60_fullHD*/, },
{    FRC_MAP_REG(REG_FRC_BK43_72_H),0xff,0x00/*OFF*/, 
                                       0x00/*4k2k*/, 
                                       0xe9/*24_60_4k2k*/, 
                                       0xe9/*30_60_4k2k*/, 
                                       0x00/*fullHD*/, 
                                       0x00/*24_60_fullHD*/, 
                                       0x00/*30_60_fullHD*/, },
{    FRC_MAP_REG(REG_FRC_BK43_73_L),0xff,0x00/*OFF*/, 
                                       0x00/*4k2k*/, 
                                       0x07/*24_60_4k2k*/, 
                                       0x07/*30_60_4k2k*/, 
                                       0x00/*fullHD*/, 
                                       0x00/*24_60_fullHD*/, 
                                       0x00/*30_60_fullHD*/, },
{    FRC_MAP_REG(REG_FRC_BK43_73_H),0x80,0x00/*OFF*/, 
                                       0x00/*4k2k*/, 
                                       0x80/*24_60_4k2k*/, 
                                       0x80/*30_60_4k2k*/, 
                                       0x00/*fullHD*/, 
                                       0x00/*24_60_fullHD*/, 
                                       0x00/*30_60_fullHD*/, },
{    FRC_MAP_REG(REG_FRC_BK43_74_L),0xff,0x00/*OFF*/, 
                                       0x00/*4k2k*/, 
                                       0x40/*24_60_4k2k*/, 
                                       0x40/*30_60_4k2k*/, 
                                       0x00/*fullHD*/, 
                                       0x00/*24_60_fullHD*/, 
                                       0x00/*30_60_fullHD*/, },
{    FRC_MAP_REG(REG_FRC_BK43_74_H),0xff,0x00/*OFF*/, 
                                       0x00/*4k2k*/, 
                                       0xfa/*24_60_4k2k*/, 
                                       0xfa/*30_60_4k2k*/, 
                                       0x00/*fullHD*/, 
                                       0x00/*24_60_fullHD*/, 
                                       0x00/*30_60_fullHD*/, },
{    FRC_MAP_REG(REG_FRC_BK43_75_L),0xff,0x00/*OFF*/, 
                                       0x00/*4k2k*/, 
                                       0x01/*24_60_4k2k*/, 
                                       0x01/*30_60_4k2k*/, 
                                       0x00/*fullHD*/, 
                                       0x00/*24_60_fullHD*/, 
                                       0x00/*30_60_fullHD*/, },
{    FRC_MAP_REG(REG_FRC_BK43_75_H),0x80,0x00/*OFF*/, 
                                       0x00/*4k2k*/, 
                                       0x80/*24_60_4k2k*/, 
                                       0x80/*30_60_4k2k*/, 
                                       0x00/*fullHD*/, 
                                       0x00/*24_60_fullHD*/, 
                                       0x00/*30_60_fullHD*/, },
{     FRC_MAP_REG(REG_TABLE_END), 0x00, 0x00 }
};

//****************************************************
// VDE
//****************************************************
MS_U8 FRC_3D_VDE_FRC_Mapping_mode[][REG_ADDR_SIZE+REG_MASK_SIZE+FRC_VDE_NUMS_FRC_Mapping_mode]=
{      // Reg           Mask  Value
{    FRC_MAP_REG(REG_FRC_BK42_50_L),0x01,0x00/*OFF*/, 
                                       0x01/*ON*/, },
{    FRC_MAP_REG(REG_FRC_BK42_51_L),0xFF,0x00/*OFF*/, 
                                       0x00/*ON*/, },
{    FRC_MAP_REG(REG_FRC_BK42_51_H),0xFF,0x00/*OFF*/, 
                                       0x0F/*ON*/, },
{     FRC_MAP_REG(REG_TABLE_END), 0x00, 0x00 }
};

//****************************************************
// 422to444
//****************************************************
MS_U8 FRC_3D_422to444_FRC_Mapping_mode[][REG_ADDR_SIZE+REG_MASK_SIZE+FRC_422to444_NUMS_FRC_Mapping_mode]=
{      // Reg           Mask  Value
{    FRC_MAP_REG(REG_FRC_BK43_51_H),0x60,0x00/*OFF*/, 
                                       0x40/*ON*/, },
{     FRC_MAP_REG(REG_TABLE_END), 0x00, 0x00 }
};

//****************************************************
// SPLT
//****************************************************
MS_U8 FRC_3D_SPLT_FRC_Mapping_mode[][REG_ADDR_SIZE+REG_MASK_SIZE+FRC_SPLT_NUMS_FRC_Mapping_mode]=
{      // Reg           Mask  Value
{    FRC_MAP_REG(REG_FRC_BK40_5A_L),0xFF,0x00/*OFF*/, 
                                       0x00/*ON*/, },
{    FRC_MAP_REG(REG_FRC_BK40_5A_H),0x1F,0x00/*OFF*/, 
                                       0x00/*ON*/, },
{    FRC_MAP_REG(REG_FRC_BK40_5B_L),0xFF,0xff/*OFF*/, 
                                       0x80/*ON*/, },
{    FRC_MAP_REG(REG_FRC_BK40_5B_H),0x1F,0x1f/*OFF*/, 
                                       0x07/*ON*/, },
{    FRC_MAP_REG(REG_FRC_BK40_5C_L),0xFF,0x00/*OFF*/, 
                                       0x08/*ON*/, },
{    FRC_MAP_REG(REG_FRC_BK40_5C_H),0x1F,0x00/*OFF*/, 
                                       0x00/*ON*/, },
{    FRC_MAP_REG(REG_FRC_BK40_5D_L),0xFF,0xff/*OFF*/, 
                                       0xff/*ON*/, },
{    FRC_MAP_REG(REG_FRC_BK40_5D_H),0x1F,0x1f/*OFF*/, 
                                       0x1f/*ON*/, },
{     FRC_MAP_REG(REG_TABLE_END), 0x00, 0x00 }
};

//****************************************************
// HVSP
//****************************************************
MS_U8 FRC_3D_HVSP_FRC_Mapping_mode[][REG_ADDR_SIZE+REG_MASK_SIZE+FRC_HVSP_NUMS_FRC_Mapping_mode]=
{      // Reg           Mask  Value
{    FRC_MAP_REG(REG_FRC_BK44_08_H),0x01,0x00/*OFF*/, 
                                       0x01/*hsp_4k_to_4k*/, 
                                       0x01/*hsp_2k_to_2k*/, 
                                       0x01/*hsp_2k_to_4k*/, 
                                       0x01/*hsp_4k_to_2k*/, },
{    FRC_MAP_REG(REG_FRC_BK44_08_L),0xff,0x00/*OFF*/, 
                                       0x10/*hsp_4k_to_4k*/, 
                                       0x10/*hsp_2k_to_2k*/, 
                                       0x08/*hsp_2k_to_4k*/, 
                                       0x20/*hsp_4k_to_2k*/, },
{    FRC_MAP_REG(REG_FRC_BK44_07_H),0xff,0x00/*OFF*/, 
                                       0x00/*hsp_4k_to_4k*/, 
                                       0x00/*hsp_2k_to_2k*/, 
                                       0x00/*hsp_2k_to_4k*/, 
                                       0x00/*hsp_4k_to_2k*/, },
{    FRC_MAP_REG(REG_FRC_BK44_07_L),0xff,0x00/*OFF*/, 
                                       0x00/*hsp_4k_to_4k*/, 
                                       0x00/*hsp_2k_to_2k*/, 
                                       0x00/*hsp_2k_to_4k*/, 
                                       0x00/*hsp_4k_to_2k*/, },
{    FRC_MAP_REG(REG_FRC_BK44_0B_L),0x01,0x00/*OFF*/, 
                                       0x00/*hsp_4k_to_4k*/, 
                                       0x00/*hsp_2k_to_2k*/, 
                                       0x01/*hsp_2k_to_4k*/, 
                                       0x01/*hsp_4k_to_2k*/, },
{    FRC_MAP_REG(REG_FRC_BK44_1A_H),0x1f,0x0f/*OFF*/, 
                                       0x0f/*hsp_4k_to_4k*/, 
                                       0x07/*hsp_2k_to_2k*/, 
                                       0x07/*hsp_2k_to_4k*/, 
                                       0x0f/*hsp_4k_to_2k*/, },
{    FRC_MAP_REG(REG_FRC_BK44_1A_L),0xff,0x00/*OFF*/, 
                                       0x00/*hsp_4k_to_4k*/, 
                                       0x80/*hsp_2k_to_2k*/, 
                                       0x80/*hsp_2k_to_4k*/, 
                                       0x00/*hsp_4k_to_2k*/, },
{    FRC_MAP_REG(REG_FRC_BK44_1B_H),0x3f,0x0f/*OFF*/, 
                                       0x0f/*hsp_4k_to_4k*/, 
                                       0x07/*hsp_2k_to_2k*/, 
                                       0x0f/*hsp_2k_to_4k*/, 
                                       0x07/*hsp_4k_to_2k*/, },
{    FRC_MAP_REG(REG_FRC_BK44_1B_L),0xff,0x00/*OFF*/, 
                                       0x00/*hsp_4k_to_4k*/, 
                                       0x80/*hsp_2k_to_2k*/, 
                                       0x00/*hsp_2k_to_4k*/, 
                                       0x80/*hsp_4k_to_2k*/, },
{     FRC_MAP_REG(REG_TABLE_END), 0x00, 0x00 }
};

//****************************************************
// VIP_HLPF
//****************************************************
MS_U8 FRC_3D_VIP_HLPF_FRC_Mapping_mode[][REG_ADDR_SIZE+REG_MASK_SIZE+FRC_VIP_HLPF_NUMS_FRC_Mapping_mode]=
{      // Reg           Mask  Value
{    FRC_MAP_REG(REG_FRC_BK47_10_L),0x70,0x00/*OFF*/, 
                                       0x10/*0x1*/, 
                                       0x20/*0x2*/, 
                                       0x30/*0x3*/, 
                                       0x40/*0x4*/, 
                                       0x50/*0x5*/, 
                                       0x60/*0x6*/, 
                                       0x70/*0x7*/, },
{     FRC_MAP_REG(REG_TABLE_END), 0x00, 0x00 }
};

//****************************************************
// VIP_HLPF_dither
//****************************************************
MS_U8 FRC_3D_VIP_HLPF_dither_FRC_Mapping_mode[][REG_ADDR_SIZE+REG_MASK_SIZE+FRC_VIP_HLPF_dither_NUMS_FRC_Mapping_mode]=
{      // Reg           Mask  Value
{    FRC_MAP_REG(REG_FRC_BK47_10_L),0x02,0x00/*OFF*/, 
                                       0x02/*ON*/, },
{     FRC_MAP_REG(REG_TABLE_END), 0x00, 0x00 }
};

//****************************************************
// VIP_Peaking
//****************************************************
MS_U8 FRC_3D_VIP_Peaking_FRC_Mapping_mode[][REG_ADDR_SIZE+REG_MASK_SIZE+FRC_VIP_Peaking_NUMS_FRC_Mapping_mode]=
{      // Reg           Mask  Value
{    FRC_MAP_REG(REG_FRC_BK47_10_L),0x01,0x00/*OFF*/, 
                                       0x01/*ON*/, },
{     FRC_MAP_REG(REG_TABLE_END), 0x00, 0x00 }
};

//****************************************************
// VIP_Peaking_band
//****************************************************
MS_U8 FRC_3D_VIP_Peaking_band_FRC_Mapping_mode[][REG_ADDR_SIZE+REG_MASK_SIZE+FRC_VIP_Peaking_band_NUMS_FRC_Mapping_mode]=
{      // Reg           Mask  Value
{    FRC_MAP_REG(REG_FRC_BK47_10_H),0x01,0xFF/*RF_NTSC*/, 
                                       0xFF/*RF_SECAM*/, 
                                       0xFF/*AV_NTSC*/, 
                                       0xFF/*AV_PAL*/, 
                                       0xFF/*AV_SECAM*/, 
                                       0xFF/*SV_NTSC*/, 
                                       0xFF/*480i*/, 
                                       0xFF/*720p*/, 
                                       0xFF/*1080i*/, 
                                       0xFF/*H_480i*/, 
                                       0xFF/*H_576i*/, 
                                       0xFF/*H_720p*/, 
                                       0xFF/*H_1080i*/, 
                                       0xFF/*DT_MPEG2_480is*/, 
                                       0xFF/*DT_MPEG2_720p*/, 
                                       0xFF/*DT_MPEG2_1080i*/, 
                                       0xFF/*DT_H264_480is*/, 
                                       0xFF/*DT_H264_720p*/, 
                                       0x00/*PC_mode*/, },
{    FRC_MAP_REG(REG_FRC_BK47_10_H),0x02,0xFF/*RF_NTSC*/, 
                                       0xFF/*RF_SECAM*/, 
                                       0xFF/*AV_NTSC*/, 
                                       0xFF/*AV_PAL*/, 
                                       0xFF/*AV_SECAM*/, 
                                       0xFF/*SV_NTSC*/, 
                                       0xFF/*480i*/, 
                                       0xFF/*720p*/, 
                                       0xFF/*1080i*/, 
                                       0xFF/*H_480i*/, 
                                       0xFF/*H_576i*/, 
                                       0xFF/*H_720p*/, 
                                       0xFF/*H_1080i*/, 
                                       0xFF/*DT_MPEG2_480is*/, 
                                       0xFF/*DT_MPEG2_720p*/, 
                                       0xFF/*DT_MPEG2_1080i*/, 
                                       0xFF/*DT_H264_480is*/, 
                                       0xFF/*DT_H264_720p*/, 
                                       0x00/*PC_mode*/, },
{    FRC_MAP_REG(REG_FRC_BK47_10_H),0x04,0xFF/*RF_NTSC*/, 
                                       0xFF/*RF_SECAM*/, 
                                       0xFF/*AV_NTSC*/, 
                                       0xFF/*AV_PAL*/, 
                                       0xFF/*AV_SECAM*/, 
                                       0xFF/*SV_NTSC*/, 
                                       0xFF/*480i*/, 
                                       0xFF/*720p*/, 
                                       0xFF/*1080i*/, 
                                       0xFF/*H_480i*/, 
                                       0xFF/*H_576i*/, 
                                       0xFF/*H_720p*/, 
                                       0xFF/*H_1080i*/, 
                                       0xFF/*DT_MPEG2_480is*/, 
                                       0xFF/*DT_MPEG2_720p*/, 
                                       0xFF/*DT_MPEG2_1080i*/, 
                                       0xFF/*DT_H264_480is*/, 
                                       0xFF/*DT_H264_720p*/, 
                                       0x00/*PC_mode*/, },
{    FRC_MAP_REG(REG_FRC_BK47_10_H),0x08,0xFF/*RF_NTSC*/, 
                                       0xFF/*RF_SECAM*/, 
                                       0xFF/*AV_NTSC*/, 
                                       0xFF/*AV_PAL*/, 
                                       0xFF/*AV_SECAM*/, 
                                       0xFF/*SV_NTSC*/, 
                                       0xFF/*480i*/, 
                                       0xFF/*720p*/, 
                                       0xFF/*1080i*/, 
                                       0xFF/*H_480i*/, 
                                       0xFF/*H_576i*/, 
                                       0xFF/*H_720p*/, 
                                       0xFF/*H_1080i*/, 
                                       0xFF/*DT_MPEG2_480is*/, 
                                       0xFF/*DT_MPEG2_720p*/, 
                                       0xFF/*DT_MPEG2_1080i*/, 
                                       0xFF/*DT_H264_480is*/, 
                                       0xFF/*DT_H264_720p*/, 
                                       0x00/*PC_mode*/, },
{    FRC_MAP_REG(REG_FRC_BK47_11_L),0x03,0x00/*RF_NTSC*/, 
                                       0x00/*RF_SECAM*/, 
                                       0x00/*AV_NTSC*/, 
                                       0x00/*AV_PAL*/, 
                                       0x01/*AV_SECAM*/, 
                                       0x01/*SV_NTSC*/, 
                                       0x00/*480i*/, 
                                       0x00/*720p*/, 
                                       0x00/*1080i*/, 
                                       0x00/*H_480i*/, 
                                       0x00/*H_576i*/, 
                                       0x00/*H_720p*/, 
                                       0x00/*H_1080i*/, 
                                       0x00/*DT_MPEG2_480is*/, 
                                       0x00/*DT_MPEG2_720p*/, 
                                       0x00/*DT_MPEG2_1080i*/, 
                                       0x00/*DT_H264_480is*/, 
                                       0x00/*DT_H264_720p*/, 
                                       0x00/*PC_mode*/, },
{    FRC_MAP_REG(REG_FRC_BK47_11_L),0x0C,0x00/*RF_NTSC*/, 
                                       0x00/*RF_SECAM*/, 
                                       0x00/*AV_NTSC*/, 
                                       0x00/*AV_PAL*/, 
                                       0x01/*AV_SECAM*/, 
                                       0x01/*SV_NTSC*/, 
                                       0x00/*480i*/, 
                                       0x00/*720p*/, 
                                       0x00/*1080i*/, 
                                       0x00/*H_480i*/, 
                                       0x00/*H_576i*/, 
                                       0x00/*H_720p*/, 
                                       0x00/*H_1080i*/, 
                                       0x00/*DT_MPEG2_480is*/, 
                                       0x00/*DT_MPEG2_720p*/, 
                                       0x00/*DT_MPEG2_1080i*/, 
                                       0x00/*DT_H264_480is*/, 
                                       0x00/*DT_H264_720p*/, 
                                       0x00/*PC_mode*/, },
{    FRC_MAP_REG(REG_FRC_BK47_11_L),0x30,0x00/*RF_NTSC*/, 
                                       0x00/*RF_SECAM*/, 
                                       0x00/*AV_NTSC*/, 
                                       0x00/*AV_PAL*/, 
                                       0x01/*AV_SECAM*/, 
                                       0x01/*SV_NTSC*/, 
                                       0x00/*480i*/, 
                                       0x00/*720p*/, 
                                       0x00/*1080i*/, 
                                       0x00/*H_480i*/, 
                                       0x00/*H_576i*/, 
                                       0x00/*H_720p*/, 
                                       0x00/*H_1080i*/, 
                                       0x00/*DT_MPEG2_480is*/, 
                                       0x00/*DT_MPEG2_720p*/, 
                                       0x00/*DT_MPEG2_1080i*/, 
                                       0x00/*DT_H264_480is*/, 
                                       0x00/*DT_H264_720p*/, 
                                       0x00/*PC_mode*/, },
{    FRC_MAP_REG(REG_FRC_BK47_11_L),0xC0,0x00/*RF_NTSC*/, 
                                       0x00/*RF_SECAM*/, 
                                       0x00/*AV_NTSC*/, 
                                       0x00/*AV_PAL*/, 
                                       0x01/*AV_SECAM*/, 
                                       0x01/*SV_NTSC*/, 
                                       0x00/*480i*/, 
                                       0x00/*720p*/, 
                                       0x00/*1080i*/, 
                                       0x00/*H_480i*/, 
                                       0x00/*H_576i*/, 
                                       0x00/*H_720p*/, 
                                       0x00/*H_1080i*/, 
                                       0x00/*DT_MPEG2_480is*/, 
                                       0x00/*DT_MPEG2_720p*/, 
                                       0x00/*DT_MPEG2_1080i*/, 
                                       0x00/*DT_H264_480is*/, 
                                       0x00/*DT_H264_720p*/, 
                                       0x00/*PC_mode*/, },
{    FRC_MAP_REG(REG_FRC_BK47_18_L),0x7F,0x28/*RF_NTSC*/, 
                                       0x28/*RF_SECAM*/, 
                                       0x20/*AV_NTSC*/, 
                                       0x20/*AV_PAL*/, 
                                       0x28/*AV_SECAM*/, 
                                       0x28/*SV_NTSC*/, 
                                       0x20/*480i*/, 
                                       0x20/*720p*/, 
                                       0x18/*1080i*/, 
                                       0x20/*H_480i*/, 
                                       0x20/*H_576i*/, 
                                       0x1A/*H_720p*/, 
                                       0x18/*H_1080i*/, 
                                       0x28/*DT_MPEG2_480is*/, 
                                       0x20/*DT_MPEG2_720p*/, 
                                       0x20/*DT_MPEG2_1080i*/, 
                                       0x28/*DT_H264_480is*/, 
                                       0x20/*DT_H264_720p*/, 
                                       0x16/*PC_mode*/, },
{    FRC_MAP_REG(REG_FRC_BK47_18_H),0x7F,0x20/*RF_NTSC*/, 
                                       0x20/*RF_SECAM*/, 
                                       0x18/*AV_NTSC*/, 
                                       0x18/*AV_PAL*/, 
                                       0x20/*AV_SECAM*/, 
                                       0x20/*SV_NTSC*/, 
                                       0x18/*480i*/, 
                                       0x18/*720p*/, 
                                       0x14/*1080i*/, 
                                       0x18/*H_480i*/, 
                                       0x18/*H_576i*/, 
                                       0x18/*H_720p*/, 
                                       0x14/*H_1080i*/, 
                                       0x20/*DT_MPEG2_480is*/, 
                                       0x1C/*DT_MPEG2_720p*/, 
                                       0x1C/*DT_MPEG2_1080i*/, 
                                       0x20/*DT_H264_480is*/, 
                                       0x1C/*DT_H264_720p*/, 
                                       0x14/*PC_mode*/, },
{    FRC_MAP_REG(REG_FRC_BK47_19_L),0x7F,0x1C/*RF_NTSC*/, 
                                       0x1C/*RF_SECAM*/, 
                                       0x10/*AV_NTSC*/, 
                                       0x10/*AV_PAL*/, 
                                       0x1C/*AV_SECAM*/, 
                                       0x1C/*SV_NTSC*/, 
                                       0x10/*480i*/, 
                                       0x10/*720p*/, 
                                       0x10/*1080i*/, 
                                       0x14/*H_480i*/, 
                                       0x14/*H_576i*/, 
                                       0x10/*H_720p*/, 
                                       0x10/*H_1080i*/, 
                                       0x1C/*DT_MPEG2_480is*/, 
                                       0x18/*DT_MPEG2_720p*/, 
                                       0x18/*DT_MPEG2_1080i*/, 
                                       0x1C/*DT_H264_480is*/, 
                                       0x18/*DT_H264_720p*/, 
                                       0x10/*PC_mode*/, },
{    FRC_MAP_REG(REG_FRC_BK47_19_H),0x7F,0x12/*RF_NTSC*/, 
                                       0x12/*RF_SECAM*/, 
                                       0x0C/*AV_NTSC*/, 
                                       0x0C/*AV_PAL*/, 
                                       0x18/*AV_SECAM*/, 
                                       0x18/*SV_NTSC*/, 
                                       0x0C/*480i*/, 
                                       0x0C/*720p*/, 
                                       0x0C/*1080i*/, 
                                       0x10/*H_480i*/, 
                                       0x10/*H_576i*/, 
                                       0x0C/*H_720p*/, 
                                       0x0C/*H_1080i*/, 
                                       0x10/*DT_MPEG2_480is*/, 
                                       0x10/*DT_MPEG2_720p*/, 
                                       0x10/*DT_MPEG2_1080i*/, 
                                       0x10/*DT_H264_480is*/, 
                                       0x10/*DT_H264_720p*/, 
                                       0x0E/*PC_mode*/, },
{    FRC_MAP_REG(REG_FRC_BK47_20_L),0xFF,0xF0/*RF_NTSC*/, 
                                       0xF0/*RF_SECAM*/, 
                                       0xA0/*AV_NTSC*/, 
                                       0xA0/*AV_PAL*/, 
                                       0xA0/*AV_SECAM*/, 
                                       0xF0/*SV_NTSC*/, 
                                       0xF0/*480i*/, 
                                       0xF0/*720p*/, 
                                       0xFF/*1080i*/, 
                                       0xA0/*H_480i*/, 
                                       0xA0/*H_576i*/, 
                                       0xF0/*H_720p*/, 
                                       0xA0/*H_1080i*/, 
                                       0xF0/*DT_MPEG2_480is*/, 
                                       0xF0/*DT_MPEG2_720p*/, 
                                       0xF0/*DT_MPEG2_1080i*/, 
                                       0xF0/*DT_H264_480is*/, 
                                       0xF0/*DT_H264_720p*/, 
                                       0xA0/*PC_mode*/, },
{    FRC_MAP_REG(REG_FRC_BK47_20_H),0xFF,0x28/*RF_NTSC*/, 
                                       0x40/*RF_SECAM*/, 
                                       0x40/*AV_NTSC*/, 
                                       0x40/*AV_PAL*/, 
                                       0x40/*AV_SECAM*/, 
                                       0x40/*SV_NTSC*/, 
                                       0x50/*480i*/, 
                                       0x40/*720p*/, 
                                       0x40/*1080i*/, 
                                       0x40/*H_480i*/, 
                                       0x40/*H_576i*/, 
                                       0x40/*H_720p*/, 
                                       0x40/*H_1080i*/, 
                                       0x48/*DT_MPEG2_480is*/, 
                                       0x48/*DT_MPEG2_720p*/, 
                                       0x28/*DT_MPEG2_1080i*/, 
                                       0x48/*DT_H264_480is*/, 
                                       0x48/*DT_H264_720p*/, 
                                       0x40/*PC_mode*/, },
{    FRC_MAP_REG(REG_FRC_BK47_21_L),0xFF,0x0A/*RF_NTSC*/, 
                                       0x04/*RF_SECAM*/, 
                                       0x04/*AV_NTSC*/, 
                                       0x04/*AV_PAL*/, 
                                       0x04/*AV_SECAM*/, 
                                       0x04/*SV_NTSC*/, 
                                       0x10/*480i*/, 
                                       0x04/*720p*/, 
                                       0x04/*1080i*/, 
                                       0x04/*H_480i*/, 
                                       0x04/*H_576i*/, 
                                       0x04/*H_720p*/, 
                                       0x04/*H_1080i*/, 
                                       0x0A/*DT_MPEG2_480is*/, 
                                       0x04/*DT_MPEG2_720p*/, 
                                       0x04/*DT_MPEG2_1080i*/, 
                                       0x0A/*DT_H264_480is*/, 
                                       0x04/*DT_H264_720p*/, 
                                       0x04/*PC_mode*/, },
{    FRC_MAP_REG(REG_FRC_BK47_21_H),0xFF,0x02/*RF_NTSC*/, 
                                       0x02/*RF_SECAM*/, 
                                       0x02/*AV_NTSC*/, 
                                       0x02/*AV_PAL*/, 
                                       0x02/*AV_SECAM*/, 
                                       0x02/*SV_NTSC*/, 
                                       0x04/*480i*/, 
                                       0x00/*720p*/, 
                                       0x02/*1080i*/, 
                                       0x02/*H_480i*/, 
                                       0x02/*H_576i*/, 
                                       0x00/*H_720p*/, 
                                       0x02/*H_1080i*/, 
                                       0x02/*DT_MPEG2_480is*/, 
                                       0x00/*DT_MPEG2_720p*/, 
                                       0x00/*DT_MPEG2_1080i*/, 
                                       0x02/*DT_H264_480is*/, 
                                       0x00/*DT_H264_720p*/, 
                                       0x00/*PC_mode*/, },
{    FRC_MAP_REG(REG_FRC_BK47_24_L),0xFF,0xF0/*RF_NTSC*/, 
                                       0xF0/*RF_SECAM*/, 
                                       0xA0/*AV_NTSC*/, 
                                       0xA0/*AV_PAL*/, 
                                       0xF0/*AV_SECAM*/, 
                                       0xF0/*SV_NTSC*/, 
                                       0xF0/*480i*/, 
                                       0xF0/*720p*/, 
                                       0xFF/*1080i*/, 
                                       0xA0/*H_480i*/, 
                                       0xA0/*H_576i*/, 
                                       0xF0/*H_720p*/, 
                                       0xA0/*H_1080i*/, 
                                       0xF0/*DT_MPEG2_480is*/, 
                                       0xF0/*DT_MPEG2_720p*/, 
                                       0xF0/*DT_MPEG2_1080i*/, 
                                       0xF0/*DT_H264_480is*/, 
                                       0xF0/*DT_H264_720p*/, 
                                       0xA0/*PC_mode*/, },
{    FRC_MAP_REG(REG_FRC_BK47_24_H),0xFF,0x50/*RF_NTSC*/, 
                                       0x50/*RF_SECAM*/, 
                                       0x40/*AV_NTSC*/, 
                                       0x40/*AV_PAL*/, 
                                       0x50/*AV_SECAM*/, 
                                       0x50/*SV_NTSC*/, 
                                       0x60/*480i*/, 
                                       0x40/*720p*/, 
                                       0x40/*1080i*/, 
                                       0x40/*H_480i*/, 
                                       0x40/*H_576i*/, 
                                       0x40/*H_720p*/, 
                                       0x40/*H_1080i*/, 
                                       0x58/*DT_MPEG2_480is*/, 
                                       0x48/*DT_MPEG2_720p*/, 
                                       0x38/*DT_MPEG2_1080i*/, 
                                       0x58/*DT_H264_480is*/, 
                                       0x48/*DT_H264_720p*/, 
                                       0x40/*PC_mode*/, },
{    FRC_MAP_REG(REG_FRC_BK47_25_L),0xFF,0x0A/*RF_NTSC*/, 
                                       0x0A/*RF_SECAM*/, 
                                       0x04/*AV_NTSC*/, 
                                       0x04/*AV_PAL*/, 
                                       0x06/*AV_SECAM*/, 
                                       0x06/*SV_NTSC*/, 
                                       0x10/*480i*/, 
                                       0x04/*720p*/, 
                                       0x04/*1080i*/, 
                                       0x04/*H_480i*/, 
                                       0x04/*H_576i*/, 
                                       0x04/*H_720p*/, 
                                       0x04/*H_1080i*/, 
                                       0x0A/*DT_MPEG2_480is*/, 
                                       0x08/*DT_MPEG2_720p*/, 
                                       0x08/*DT_MPEG2_1080i*/, 
                                       0x0A/*DT_H264_480is*/, 
                                       0x08/*DT_H264_720p*/, 
                                       0x04/*PC_mode*/, },
{    FRC_MAP_REG(REG_FRC_BK47_25_H),0xFF,0x02/*RF_NTSC*/, 
                                       0x02/*RF_SECAM*/, 
                                       0x02/*AV_NTSC*/, 
                                       0x02/*AV_PAL*/, 
                                       0x02/*AV_SECAM*/, 
                                       0x02/*SV_NTSC*/, 
                                       0x04/*480i*/, 
                                       0x00/*720p*/, 
                                       0x02/*1080i*/, 
                                       0x02/*H_480i*/, 
                                       0x02/*H_576i*/, 
                                       0x00/*H_720p*/, 
                                       0x02/*H_1080i*/, 
                                       0x02/*DT_MPEG2_480is*/, 
                                       0x00/*DT_MPEG2_720p*/, 
                                       0x00/*DT_MPEG2_1080i*/, 
                                       0x02/*DT_H264_480is*/, 
                                       0x00/*DT_H264_720p*/, 
                                       0x00/*PC_mode*/, },
{     FRC_MAP_REG(REG_TABLE_END), 0x00, 0x00 }
};

//****************************************************
// VIP_Peaking_Pcoring
//****************************************************
MS_U8 FRC_3D_VIP_Peaking_Pcoring_FRC_Mapping_mode[][REG_ADDR_SIZE+REG_MASK_SIZE+FRC_VIP_Peaking_Pcoring_NUMS_FRC_Mapping_mode]=
{      // Reg           Mask  Value
{    FRC_MAP_REG(REG_FRC_BK47_13_L),0x0F,0x00/*S00_0*/, 
                                       0x01/*S21_1*/, 
                                       0x00/*S30_0*/, 
                                       0x00/*S30_1*/, 
                                       0x01/*S31_0*/, 
                                       0x01/*S31_1*/, 
                                       0x01/*S20_1*/, 
                                       0x02/*S32_0*/, 
                                       0x02/*S32_1*/, 
                                       0x02/*S42_1*/, },
{    FRC_MAP_REG(REG_FRC_BK47_13_L),0xF0,0x00/*S00_0*/, 
                                       0x20/*S21_1*/, 
                                       0x30/*S30_0*/, 
                                       0x30/*S30_1*/, 
                                       0x30/*S31_0*/, 
                                       0x30/*S31_1*/, 
                                       0x20/*S20_1*/, 
                                       0x30/*S32_0*/, 
                                       0x30/*S32_1*/, 
                                       0x40/*S42_1*/, },
{    FRC_MAP_REG(REG_FRC_BK47_30_H),0x30,0x00/*S00_0*/, 
                                       0x10/*S21_1*/, 
                                       0x00/*S30_0*/, 
                                       0x10/*S30_1*/, 
                                       0x00/*S31_0*/, 
                                       0x10/*S31_1*/, 
                                       0x10/*S20_1*/, 
                                       0x00/*S32_0*/, 
                                       0x10/*S32_1*/, 
                                       0x10/*S42_1*/, },
{     FRC_MAP_REG(REG_TABLE_END), 0x00, 0x00 }
};

//****************************************************
// VIP_Peaking_gain
//****************************************************
MS_U8 FRC_3D_VIP_Peaking_gain_FRC_Mapping_mode[][REG_ADDR_SIZE+REG_MASK_SIZE+FRC_VIP_Peaking_gain_NUMS_FRC_Mapping_mode]=
{      // Reg           Mask  Value
{    FRC_MAP_REG(REG_FRC_BK47_13_H),0x3F,0x18/*0x18*/, 
                                       0x1C/*0x1C*/, 
                                       0x20/*0x20*/, 
                                       0x24/*0x24*/, 
                                       0x28/*0x28*/, 
                                       0x2C/*0x2C*/, 
                                       0x30/*0x30*/, 
                                       0x34/*0x34*/, 
                                       0x38/*0x38*/, },
{     FRC_MAP_REG(REG_TABLE_END), 0x00, 0x00 }
};

//****************************************************
// Y2R
//****************************************************
MS_U8 FRC_3D_Y2R_FRC_Mapping_mode[][REG_ADDR_SIZE+REG_MASK_SIZE+FRC_Y2R_NUMS_FRC_Mapping_mode]=
{      // Reg           Mask  Value
{    FRC_MAP_REG(REG_FRC_BK47_50_L),0x01,0x00/*OFF*/, 
                                       0x01/*ON*/, },
{    FRC_MAP_REG(REG_FRC_BK47_50_L),0x02,0x00/*OFF*/, 
                                       0x02/*ON*/, },
{     FRC_MAP_REG(REG_TABLE_END), 0x00, 0x00 }
};


code EN_FRC_IPTAB_INFO FRC_IPTAB_INFO_FRC_Mapping_mode[]=
{
{ *FRC_3D_R2Y_FRC_Mapping_mode, FRC_R2Y_NUMS_FRC_Mapping_mode},
{ *FRC_3D_MRW_FRC_Mapping_mode, FRC_MRW_NUMS_FRC_Mapping_mode},
{ *FRC_3D_HSD_FRC_Mapping_mode, FRC_HSD_NUMS_FRC_Mapping_mode},
{ *FRC_3D_444to422_FRC_Mapping_mode, FRC_444to422_NUMS_FRC_Mapping_mode},
{ *FRC_3D_VCE_FRC_Mapping_mode, FRC_VCE_NUMS_FRC_Mapping_mode},
{ *FRC_3D_IPM_OPM_FRC_Mapping_mode, FRC_IPM_OPM_NUMS_FRC_Mapping_mode},
{ *FRC_3D_VDE_FRC_Mapping_mode, FRC_VDE_NUMS_FRC_Mapping_mode},
{ *FRC_3D_422to444_FRC_Mapping_mode, FRC_422to444_NUMS_FRC_Mapping_mode},
{ *FRC_3D_SPLT_FRC_Mapping_mode, FRC_SPLT_NUMS_FRC_Mapping_mode},
{ *FRC_3D_HVSP_FRC_Mapping_mode, FRC_HVSP_NUMS_FRC_Mapping_mode},
{ *FRC_3D_VIP_HLPF_FRC_Mapping_mode, FRC_VIP_HLPF_NUMS_FRC_Mapping_mode},
{ *FRC_3D_VIP_HLPF_dither_FRC_Mapping_mode, FRC_VIP_HLPF_dither_NUMS_FRC_Mapping_mode},
{ *FRC_3D_VIP_Peaking_FRC_Mapping_mode, FRC_VIP_Peaking_NUMS_FRC_Mapping_mode},
{ *FRC_3D_VIP_Peaking_band_FRC_Mapping_mode, FRC_VIP_Peaking_band_NUMS_FRC_Mapping_mode},
{ *FRC_3D_VIP_Peaking_Pcoring_FRC_Mapping_mode, FRC_VIP_Peaking_Pcoring_NUMS_FRC_Mapping_mode},
{ *FRC_3D_VIP_Peaking_gain_FRC_Mapping_mode, FRC_VIP_Peaking_gain_NUMS_FRC_Mapping_mode},
{ *FRC_3D_Y2R_FRC_Mapping_mode, FRC_Y2R_NUMS_FRC_Mapping_mode},
};

#endif
