
#if PQ_GRULE_UFSC_MPEG_NR_ENABLE
code U8 MST_GRule_MPEG_NR_IP_Index_UFSC[PQ_GRULE_MPEG_NR_IP_NUM_UFSC]=
{
    PQ_IP_DMS_UFSC,
    PQ_IP_DMS_H_UFSC,
    PQ_IP_DMS_V_UFSC,
};
#endif


#if PQ_GRULE_UFSC_DYNAMIC_CONTRAST_ENABLE
code U8 MST_GRule_DYNAMIC_CONTRAST_IP_Index_UFSC[PQ_GRULE_DYNAMIC_CONTRAST_IP_NUM_UFSC]=
{
    PQ_IP_VIP_DLC_UFSC,
};
#endif


#if PQ_GRULE_UFSC_SR_CONTROL_ENABLE
code U8 MST_GRule_SR_CONTROL_IP_Index_UFSC[PQ_GRULE_SR_CONTROL_IP_NUM_UFSC]=
{
    PQ_IP_PreEnhance_PK3x3_UFSC,
    PQ_IP_AA_UFSC,
    PQ_IP_ERC_UFSC,
    PQ_IP_P2M_UFSC,
    PQ_IP_DS_UFSC,
    PQ_IP_VIP_Post3x3PK_UFSC,
};
#endif


#if PQ_GRULE_UFSC_DS_PARAMETERS_ENABLE
code U8 MST_GRule_DS_PARAMETERS_IP_Index_UFSC[PQ_GRULE_DS_PARAMETERS_IP_NUM_UFSC]=
{
    PQ_IP_PreEnhance_UFSC,
    PQ_IP_ANN_UFSC,
    PQ_IP_ERC_UFSC,
    PQ_IP_VIP_Peaking_UFSC,
    PQ_IP_VIP_Peaking_SecAC_UFSC,
};
#endif


#if PQ_GRULE_UFSC_HDR_ENABLE
code U8 MST_GRule_HDR_IP_Index_UFSC[PQ_GRULE_HDR_IP_NUM_UFSC]=
{
    PQ_IP_SPF_UFSC,
    PQ_IP_VIP_LCE_UFSC,
    PQ_IP_VIP_DLC_UFSC,
    PQ_IP_VIP_BWLE_UFSC,
    PQ_IP_SWDriver_UFSC,
};
#endif


#if PQ_GRULE_UFSC_MPEG_NR_ENABLE
code U8 MST_GRule_MPEG_NR_UFSC[QM_INPUTTYPE_NUM_UFSC][PQ_GRULE_MPEG_NR_NUM_UFSC][PQ_GRULE_MPEG_NR_IP_NUM_UFSC]=
{
    #if PQ_QM_HMDI
    {//4K2K_RGB444, 0
        {//Off
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Low
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Middle
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//High
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//4K2K_YUV444, 1
        {//Off
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Low
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Middle
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//High
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//4K2K_YUV422, 2
        {//Off
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Low
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Middle
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//High
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_RGB444, 3
        {//Off
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Low
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Middle
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//High
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_YUV444, 4
        {//Off
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Low
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Middle
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//High
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_YUV422, 5
        {//Off
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Low
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Middle
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//High
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FSC_3D, 6
        {//Off
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Low
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Middle
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//High
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//4K2K_RGB444_DS, 7
        {//Off
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Low
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Middle
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//High
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//4K2K_YUV444_DS, 8
        {//Off
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Low
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Middle
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//High
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//4K2K_YUV422_DS, 9
        {//Off
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Low
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Middle
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//High
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_RGB444_DS, 10
        {//Off
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Low
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Middle
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//High
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_YUV444_DS, 11
        {//Off
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Low
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Middle
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//High
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_YUV422_DS, 12
        {//Off
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Low
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Middle
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//High
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FSC_3D_DS, 13
        {//Off
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Low
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Middle
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//High
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//4K2K_PQbypass, 14
        {//Off
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Low
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Middle
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//High
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_PQBypass, 15
        {//Off
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Low
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//Middle
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
        {//High
            PQ_IP_DMS_OFF_UFSC,
            PQ_IP_DMS_H_OFF_UFSC,
            PQ_IP_DMS_V_OFF_UFSC,
        },
    },
    #endif
};
#endif


#if PQ_GRULE_UFSC_DYNAMIC_CONTRAST_ENABLE
code U8 MST_GRule_DYNAMIC_CONTRAST_UFSC[QM_INPUTTYPE_NUM_UFSC][PQ_GRULE_DYNAMIC_CONTRAST_NUM_UFSC][PQ_GRULE_DYNAMIC_CONTRAST_IP_NUM_UFSC]=
{
    #if PQ_QM_HMDI
    {//4K2K_RGB444, 0
        {//Off
            PQ_IP_VIP_DLC_OFF_UFSC,
        },
        {//On
            PQ_IP_VIP_DLC_ON_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//4K2K_YUV444, 1
        {//Off
            PQ_IP_VIP_DLC_OFF_UFSC,
        },
        {//On
            PQ_IP_VIP_DLC_ON_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//4K2K_YUV422, 2
        {//Off
            PQ_IP_VIP_DLC_OFF_UFSC,
        },
        {//On
            PQ_IP_VIP_DLC_ON_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_RGB444, 3
        {//Off
            PQ_IP_VIP_DLC_OFF_UFSC,
        },
        {//On
            PQ_IP_VIP_DLC_ON_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_YUV444, 4
        {//Off
            PQ_IP_VIP_DLC_OFF_UFSC,
        },
        {//On
            PQ_IP_VIP_DLC_ON_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_YUV422, 5
        {//Off
            PQ_IP_VIP_DLC_OFF_UFSC,
        },
        {//On
            PQ_IP_VIP_DLC_ON_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FSC_3D, 6
        {//Off
            PQ_IP_VIP_DLC_OFF_UFSC,
        },
        {//On
            PQ_IP_VIP_DLC_ON_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//4K2K_RGB444_DS, 7
        {//Off
            PQ_IP_VIP_DLC_OFF_UFSC,
        },
        {//On
            PQ_IP_VIP_DLC_ON_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//4K2K_YUV444_DS, 8
        {//Off
            PQ_IP_VIP_DLC_OFF_UFSC,
        },
        {//On
            PQ_IP_VIP_DLC_ON_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//4K2K_YUV422_DS, 9
        {//Off
            PQ_IP_VIP_DLC_OFF_UFSC,
        },
        {//On
            PQ_IP_VIP_DLC_ON_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_RGB444_DS, 10
        {//Off
            PQ_IP_VIP_DLC_OFF_UFSC,
        },
        {//On
            PQ_IP_VIP_DLC_ON_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_YUV444_DS, 11
        {//Off
            PQ_IP_VIP_DLC_OFF_UFSC,
        },
        {//On
            PQ_IP_VIP_DLC_ON_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_YUV422_DS, 12
        {//Off
            PQ_IP_VIP_DLC_OFF_UFSC,
        },
        {//On
            PQ_IP_VIP_DLC_ON_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FSC_3D_DS, 13
        {//Off
            PQ_IP_VIP_DLC_OFF_UFSC,
        },
        {//On
            PQ_IP_VIP_DLC_ON_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//4K2K_PQbypass, 14
        {//Off
            PQ_IP_VIP_DLC_OFF_UFSC,
        },
        {//On
            PQ_IP_VIP_DLC_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_PQBypass, 15
        {//Off
            PQ_IP_VIP_DLC_OFF_UFSC,
        },
        {//On
            PQ_IP_VIP_DLC_OFF_UFSC,
        },
    },
    #endif
};
#endif


#if PQ_GRULE_UFSC_SR_CONTROL_ENABLE
code U8 MST_GRule_SR_CONTROL_UFSC[QM_INPUTTYPE_NUM_UFSC][PQ_GRULE_SR_CONTROL_NUM_UFSC][PQ_GRULE_SR_CONTROL_IP_NUM_UFSC]=
{
    #if PQ_QM_HMDI
    {//4K2K_RGB444, 0
        {//Off
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_OFF_UFSC,
            PQ_IP_DS_OFF_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Low
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_SR_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Middle
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_S1_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_W0_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//On_High
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_S1_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_W1_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//4K2K_YUV444, 1
        {//Off
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_OFF_UFSC,
            PQ_IP_DS_OFF_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Low
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_SR_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Middle
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_S1_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_W0_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//On_High
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_S1_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_W1_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//4K2K_YUV422, 2
        {//Off
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_OFF_UFSC,
            PQ_IP_DS_OFF_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Low
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_SR_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Middle
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_S1_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_W0_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//On_High
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_S1_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_W1_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_RGB444, 3
        {//Off
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_OFF_UFSC,
            PQ_IP_DS_OFF_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Low
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_SR_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Middle
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_S1_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_W0_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//On_High
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_S1_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_W1_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_YUV444, 4
        {//Off
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_OFF_UFSC,
            PQ_IP_DS_OFF_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Low
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_SR_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Middle
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_S1_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_W0_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//On_High
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_S1_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_W1_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_YUV422, 5
        {//Off
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_OFF_UFSC,
            PQ_IP_DS_OFF_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Low
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_SR_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Middle
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_S1_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_W0_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//On_High
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_S1_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_W1_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FSC_3D, 6
        {//Off
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_OFF_UFSC,
            PQ_IP_DS_OFF_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Low
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_OFF_UFSC,
            PQ_IP_DS_OFF_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Middle
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_OFF_UFSC,
            PQ_IP_DS_OFF_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//On_High
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_OFF_UFSC,
            PQ_IP_DS_OFF_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//4K2K_RGB444_DS, 7
        {//Off
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_OFF_UFSC,
            PQ_IP_DS_OFF_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Low
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_SR_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Middle
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_S1_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_W0_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//On_High
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_S1_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_W1_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//4K2K_YUV444_DS, 8
        {//Off
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_OFF_UFSC,
            PQ_IP_DS_OFF_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Low
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_SR_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Middle
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_S1_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_W0_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//On_High
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_S1_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_W1_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//4K2K_YUV422_DS, 9
        {//Off
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_OFF_UFSC,
            PQ_IP_DS_OFF_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Low
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_SR_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Middle
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_S1_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_W0_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//On_High
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_S1_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_W1_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_RGB444_DS, 10
        {//Off
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_OFF_UFSC,
            PQ_IP_DS_OFF_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Low
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_SR_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Middle
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_S1_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_W0_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//On_High
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_S1_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_W1_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_YUV444_DS, 11
        {//Off
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_OFF_UFSC,
            PQ_IP_DS_OFF_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Low
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_SR_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Middle
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_S1_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_W0_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//On_High
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_S1_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_W1_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_YUV422_DS, 12
        {//Off
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_OFF_UFSC,
            PQ_IP_DS_OFF_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Low
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_SR_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Middle
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_S1_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_W0_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//On_High
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_S1_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_W1_UFSC,
            PQ_IP_DS_W1_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FSC_3D_DS, 13
        {//Off
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_OFF_UFSC,
            PQ_IP_DS_OFF_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Low
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_OFF_UFSC,
            PQ_IP_DS_OFF_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Middle
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_OFF_UFSC,
            PQ_IP_DS_OFF_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//On_High
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_OFF_UFSC,
            PQ_IP_DS_OFF_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//4K2K_PQbypass, 14
        {//Off
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_OFF_UFSC,
            PQ_IP_DS_OFF_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Low
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_OFF_UFSC,
            PQ_IP_DS_OFF_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Middle
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_OFF_UFSC,
            PQ_IP_DS_OFF_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//On_High
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_OFF_UFSC,
            PQ_IP_DS_OFF_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_PQBypass, 15
        {//Off
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_OFF_UFSC,
            PQ_IP_DS_OFF_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Low
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_OFF_UFSC,
            PQ_IP_DS_OFF_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//Middle
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_OFF_UFSC,
            PQ_IP_DS_OFF_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
        {//On_High
            PQ_IP_PreEnhance_PK3x3_OFF_UFSC,
            PQ_IP_AA_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_P2M_OFF_UFSC,
            PQ_IP_DS_OFF_UFSC,
            PQ_IP_VIP_Post3x3PK_OFF_UFSC,
        },
    },
    #endif
};
#endif


#if PQ_GRULE_UFSC_DS_PARAMETERS_ENABLE
code U8 MST_GRule_DS_PARAMETERS_UFSC[QM_INPUTTYPE_NUM_UFSC][PQ_GRULE_DS_PARAMETERS_NUM_UFSC][PQ_GRULE_DS_PARAMETERS_IP_NUM_UFSC]=
{
    #if PQ_QM_HMDI
    {//4K2K_RGB444, 0
        {//L_SD
            PQ_IP_PreEnhance_OFF_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
        {//SD
            PQ_IP_PreEnhance_OFF_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
        {//FHD
            PQ_IP_PreEnhance_OFF_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
        {//4K
            PQ_IP_PreEnhance_OFF_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//4K2K_YUV444, 1
        {//L_SD
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
        {//SD
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
        {//FHD
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
        {//4K
            PQ_IP_PreEnhance_OFF_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//4K2K_YUV422, 2
        {//L_SD
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
        {//SD
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
        {//FHD
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
        {//4K
            PQ_IP_PreEnhance_OFF_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_RGB444, 3
        {//L_SD
            PQ_IP_PreEnhance_OFF_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
        {//SD
            PQ_IP_PreEnhance_OFF_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
        {//FHD
            PQ_IP_PreEnhance_OFF_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
        {//4K
            PQ_IP_PreEnhance_OFF_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_YUV444, 4
        {//L_SD
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_S1_UFSC,
            PQ_IP_ERC_SmallAC_UFSC,
            PQ_IP_VIP_Peaking_ON_UFSC,
            PQ_IP_VIP_Peaking_SecAC_M1208_UFSC,
        },
        {//SD
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_S1_UFSC,
            PQ_IP_ERC_SmallAC_UFSC,
            PQ_IP_VIP_Peaking_ON_UFSC,
            PQ_IP_VIP_Peaking_SecAC_M1208_UFSC,
        },
        {//FHD
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_S1_UFSC,
            PQ_IP_ERC_SmallAC_UFSC,
            PQ_IP_VIP_Peaking_ON_UFSC,
            PQ_IP_VIP_Peaking_SecAC_M1208_UFSC,
        },
        {//4K
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_S1_UFSC,
            PQ_IP_ERC_SmallAC_UFSC,
            PQ_IP_VIP_Peaking_ON_UFSC,
            PQ_IP_VIP_Peaking_SecAC_M1208_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_YUV422, 5
        {//L_SD
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_S1_UFSC,
            PQ_IP_ERC_SmallAC_UFSC,
            PQ_IP_VIP_Peaking_ON_UFSC,
            PQ_IP_VIP_Peaking_SecAC_M1208_UFSC,
        },
        {//SD
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_S1_UFSC,
            PQ_IP_ERC_SmallAC_UFSC,
            PQ_IP_VIP_Peaking_ON_UFSC,
            PQ_IP_VIP_Peaking_SecAC_M1208_UFSC,
        },
        {//FHD
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_S1_UFSC,
            PQ_IP_ERC_SmallAC_UFSC,
            PQ_IP_VIP_Peaking_ON_UFSC,
            PQ_IP_VIP_Peaking_SecAC_M1208_UFSC,
        },
        {//4K
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_S1_UFSC,
            PQ_IP_ERC_SmallAC_UFSC,
            PQ_IP_VIP_Peaking_ON_UFSC,
            PQ_IP_VIP_Peaking_SecAC_M1208_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FSC_3D, 6
        {//L_SD
            PQ_IP_PreEnhance_OFF_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
        {//SD
            PQ_IP_PreEnhance_OFF_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
        {//FHD
            PQ_IP_PreEnhance_OFF_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
        {//4K
            PQ_IP_PreEnhance_OFF_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//4K2K_RGB444_DS, 7
        {//L_SD
            PQ_IP_PreEnhance_OFF_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
        {//SD
            PQ_IP_PreEnhance_OFF_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
        {//FHD
            PQ_IP_PreEnhance_OFF_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
        {//4K
            PQ_IP_PreEnhance_OFF_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//4K2K_YUV444_DS, 8
        {//L_SD
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_S1_UFSC,
            PQ_IP_ERC_SmallAC_UFSC,
            PQ_IP_VIP_Peaking_ON_UFSC,
            PQ_IP_VIP_Peaking_SecAC_M1208_UFSC,
        },
        {//SD
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_S1_UFSC,
            PQ_IP_ERC_SmallAC_UFSC,
            PQ_IP_VIP_Peaking_ON_UFSC,
            PQ_IP_VIP_Peaking_SecAC_M1208_UFSC,
        },
        {//FHD
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_S1_UFSC,
            PQ_IP_ERC_SmallAC_UFSC,
            PQ_IP_VIP_Peaking_ON_UFSC,
            PQ_IP_VIP_Peaking_SecAC_M1208_UFSC,
        },
        {//4K
            PQ_IP_PreEnhance_OFF_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//4K2K_YUV422_DS, 9
        {//L_SD
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_S1_UFSC,
            PQ_IP_ERC_SmallAC_UFSC,
            PQ_IP_VIP_Peaking_ON_UFSC,
            PQ_IP_VIP_Peaking_SecAC_M1208_UFSC,
        },
        {//SD
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_S1_UFSC,
            PQ_IP_ERC_SmallAC_UFSC,
            PQ_IP_VIP_Peaking_ON_UFSC,
            PQ_IP_VIP_Peaking_SecAC_M1208_UFSC,
        },
        {//FHD
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_S1_UFSC,
            PQ_IP_ERC_SmallAC_UFSC,
            PQ_IP_VIP_Peaking_ON_UFSC,
            PQ_IP_VIP_Peaking_SecAC_M1208_UFSC,
        },
        {//4K
            PQ_IP_PreEnhance_OFF_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_RGB444_DS, 10
        {//L_SD
            PQ_IP_PreEnhance_OFF_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
        {//SD
            PQ_IP_PreEnhance_OFF_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
        {//FHD
            PQ_IP_PreEnhance_OFF_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
        {//4K
            PQ_IP_PreEnhance_OFF_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_YUV444_DS, 11
        {//L_SD
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_S1_UFSC,
            PQ_IP_ERC_SmallAC_UFSC,
            PQ_IP_VIP_Peaking_ON_UFSC,
            PQ_IP_VIP_Peaking_SecAC_M1208_UFSC,
        },
        {//SD
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_S1_UFSC,
            PQ_IP_ERC_SmallAC_UFSC,
            PQ_IP_VIP_Peaking_ON_UFSC,
            PQ_IP_VIP_Peaking_SecAC_M1208_UFSC,
        },
        {//FHD
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_S1_UFSC,
            PQ_IP_ERC_SmallAC_UFSC,
            PQ_IP_VIP_Peaking_ON_UFSC,
            PQ_IP_VIP_Peaking_SecAC_M1208_UFSC,
        },
        {//4K
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_S1_UFSC,
            PQ_IP_ERC_SmallAC_UFSC,
            PQ_IP_VIP_Peaking_ON_UFSC,
            PQ_IP_VIP_Peaking_SecAC_M1208_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_YUV422_DS, 12
        {//L_SD
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_S1_UFSC,
            PQ_IP_ERC_SmallAC_UFSC,
            PQ_IP_VIP_Peaking_ON_UFSC,
            PQ_IP_VIP_Peaking_SecAC_M1208_UFSC,
        },
        {//SD
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_S1_UFSC,
            PQ_IP_ERC_SmallAC_UFSC,
            PQ_IP_VIP_Peaking_ON_UFSC,
            PQ_IP_VIP_Peaking_SecAC_M1208_UFSC,
        },
        {//FHD
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_S1_UFSC,
            PQ_IP_ERC_SmallAC_UFSC,
            PQ_IP_VIP_Peaking_ON_UFSC,
            PQ_IP_VIP_Peaking_SecAC_M1208_UFSC,
        },
        {//4K
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_S1_UFSC,
            PQ_IP_ERC_SmallAC_UFSC,
            PQ_IP_VIP_Peaking_ON_UFSC,
            PQ_IP_VIP_Peaking_SecAC_M1208_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FSC_3D_DS, 13
        {//L_SD
            PQ_IP_PreEnhance_OFF_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
        {//SD
            PQ_IP_PreEnhance_OFF_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
        {//FHD
            PQ_IP_PreEnhance_OFF_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
        {//4K
            PQ_IP_PreEnhance_OFF_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//4K2K_PQbypass, 14
        {//L_SD
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
        {//SD
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
        {//FHD
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
        {//4K
            PQ_IP_PreEnhance_OFF_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_PQBypass, 15
        {//L_SD
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_M1208_UFSC,
        },
        {//SD
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_M1208_UFSC,
        },
        {//FHD
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_M1208_UFSC,
        },
        {//4K
            PQ_IP_PreEnhance_ON_UFSC,
            PQ_IP_ANN_OFF_UFSC,
            PQ_IP_ERC_OFF_UFSC,
            PQ_IP_VIP_Peaking_OFF_UFSC,
            PQ_IP_VIP_Peaking_SecAC_M1208_UFSC,
        },
    },
    #endif
};
#endif


#if PQ_GRULE_UFSC_HDR_ENABLE
code U8 MST_GRule_HDR_UFSC[QM_INPUTTYPE_NUM_UFSC][PQ_GRULE_HDR_NUM_UFSC][PQ_GRULE_HDR_IP_NUM_UFSC]=
{
    #if PQ_QM_HMDI
    {//4K2K_RGB444, 0
        {//On
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//Ref
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_1920
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_1366
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_4K
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//Dolby_ON
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_HDR_SROFF_UFSC,
        },
        {//Dolby_User
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//4K2K_YUV444, 1
        {//On
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_ON_parallel_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//Ref
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_1920
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_ON_parallel_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_1366
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_ON_parallel_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_4K
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_ON_parallel_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//Dolby_ON
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_HDR_SROFF_UFSC,
        },
        {//Dolby_User
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//4K2K_YUV422, 2
        {//On
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_ON_parallel_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//Ref
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_1920
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_ON_parallel_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_1366
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_ON_parallel_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_4K
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_ON_parallel_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//Dolby_ON
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_HDR_SROFF_UFSC,
        },
        {//Dolby_User
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_RGB444, 3
        {//On
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//Ref
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_1920
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_1366
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_4K
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//Dolby_ON
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_HDR_SROFF_UFSC,
        },
        {//Dolby_User
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_YUV444, 4
        {//On
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_Lrange_0323_UFSC,
        },
        {//Ref
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_Lrange_0323_UFSC,
        },
        {//HDR_OFF_1920
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_Lrange_0323_UFSC,
        },
        {//HDR_OFF_1366
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_Lrange_0216_UFSC,
        },
        {//HDR_OFF_4K
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_Lrange_0323_UFSC,
        },
        {//Dolby_ON
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_HDR_SROFF_UFSC,
        },
        {//Dolby_User
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_Lrange_0323_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_YUV422, 5
        {//On
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_Lrange_0323_UFSC,
        },
        {//Ref
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_Lrange_0323_UFSC,
        },
        {//HDR_OFF_1920
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_Lrange_0323_UFSC,
        },
        {//HDR_OFF_1366
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_Lrange_0216_UFSC,
        },
        {//HDR_OFF_4K
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_Lrange_0323_UFSC,
        },
        {//Dolby_ON
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_HDR_SROFF_UFSC,
        },
        {//Dolby_User
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_Lrange_0323_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FSC_3D, 6
        {//On
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//Ref
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_1920
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_1366
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_4K
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//Dolby_ON
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_HDR_SROFF_UFSC,
        },
        {//Dolby_User
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//4K2K_RGB444_DS, 7
        {//On
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//Ref
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_1920
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_1366
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_4K
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//Dolby_ON
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_HDR_SROFF_UFSC,
        },
        {//Dolby_User
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//4K2K_YUV444_DS, 8
        {//On
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_ON_parallel_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//Ref
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_1920
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_ON_parallel_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_1366
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_ON_parallel_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_4K
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_ON_parallel_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//Dolby_ON
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_HDR_SROFF_UFSC,
        },
        {//Dolby_User
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//4K2K_YUV422_DS, 9
        {//On
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_ON_parallel_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//Ref
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_1920
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_ON_parallel_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_1366
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_ON_parallel_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_4K
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_ON_parallel_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//Dolby_ON
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_HDR_SROFF_UFSC,
        },
        {//Dolby_User
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_RGB444_DS, 10
        {//On
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//Ref
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_1920
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_1366
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_4K
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//Dolby_ON
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_HDR_SROFF_UFSC,
        },
        {//Dolby_User
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_YUV444_DS, 11
        {//On
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_Lrange_0323_UFSC,
        },
        {//Ref
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_Lrange_0323_UFSC,
        },
        {//HDR_OFF_1920
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_Lrange_0323_UFSC,
        },
        {//HDR_OFF_1366
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_Lrange_0216_UFSC,
        },
        {//HDR_OFF_4K
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_Lrange_0323_UFSC,
        },
        {//Dolby_ON
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_HDR_SROFF_UFSC,
        },
        {//Dolby_User
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_Lrange_0323_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_YUV422_DS, 12
        {//On
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_Lrange_0323_UFSC,
        },
        {//Ref
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_Lrange_0323_UFSC,
        },
        {//HDR_OFF_1920
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_Lrange_0323_UFSC,
        },
        {//HDR_OFF_1366
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_Lrange_0216_UFSC,
        },
        {//HDR_OFF_4K
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_ON_UFSC,
            PQ_IP_SWDriver_Lrange_0323_UFSC,
        },
        {//Dolby_ON
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_HDR_SROFF_UFSC,
        },
        {//Dolby_User
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_Lrange_0323_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FSC_3D_DS, 13
        {//On
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//Ref
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_1920
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_1366
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_4K
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_ON_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//Dolby_ON
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_HDR_SROFF_UFSC,
        },
        {//Dolby_User
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//4K2K_PQbypass, 14
        {//On
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//Ref
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_1920
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_1366
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_4K
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//Dolby_ON
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_HDR_SROFF_UFSC,
        },
        {//Dolby_User
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
    },
    #endif
    #if PQ_QM_HMDI
    {//FHD_PQBypass, 15
        {//On
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//Ref
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_1920
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_1366
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//HDR_OFF_4K
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
        {//Dolby_ON
            PQ_IP_SPF_OFF_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_HDR_SROFF_UFSC,
        },
        {//Dolby_User
            PQ_IP_SPF_ON_UFSC,
            PQ_IP_VIP_LCE_OFF_UFSC,
            PQ_IP_VIP_DLC_OFF_UFSC,
            PQ_IP_VIP_BWLE_OFF_UFSC,
            PQ_IP_SWDriver_OFF_UFSC,
        },
    },
    #endif
};
#endif

