#ifndef _UTOPIA_MODULE_H_
#define _UTOPIA_MODULE_H_

#include "MsTypes.h"

enum {
	UTOPIA_POOL_ID_DATA,
} eUtopiaPoolID;

MS_U32 _UtopiaModule_Ioctl(void** pInstant, MS_U32 u32Cmd, MS_U32* pu32Args);
MS_U32 UTOPIARegisterToUtopia(FUtopiaOpen ModuleType);

enum {
	CHANGE_DEBUG_LEVEL_BY_MODULE,
	HOOK_MODULE_IOCTL_BY_MODULE,
	HOOK_MODULE_CMD_BY_MODULE,
	DUMP_MODULE_HW_REGISTER,
	DUMP_MODULE_STRUCTURE,
	DUMP_INSTANT_STRUCTURE,
	DUMP2MEMORY_MODULE_HW_REGISTER,
	DUMP2MEMORY_MODULE_STRUCTURE,
	DUMP2MEMORY_INSTANT_STRUCTURE,
	SHOW_RESOURCE_STATUS_BY_MODULE,
} eUtopiaModuleIoctlOpt;

#endif
